// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/v3/models/components"
)

type AgentsControllerUpdateAgentRequest struct {
	Identifier string `pathParam:"style=simple,explode=false,name=identifier"`
	// A header for idempotency purposes
	IdempotencyKey        *string                          `header:"style=simple,explode=false,name=idempotency-key"`
	UpdateAgentRequestDto components.UpdateAgentRequestDto `request:"mediaType=application/json"`
}

func (a *AgentsControllerUpdateAgentRequest) GetIdentifier() string {
	if a == nil {
		return ""
	}
	return a.Identifier
}

func (a *AgentsControllerUpdateAgentRequest) GetIdempotencyKey() *string {
	if a == nil {
		return nil
	}
	return a.IdempotencyKey
}

func (a *AgentsControllerUpdateAgentRequest) GetUpdateAgentRequestDto() components.UpdateAgentRequestDto {
	if a == nil {
		return components.UpdateAgentRequestDto{}
	}
	return a.UpdateAgentRequestDto
}

type AgentsControllerUpdateAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AgentResponseDto *components.AgentResponseDto
	Headers          map[string][]string
}

func (a *AgentsControllerUpdateAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AgentsControllerUpdateAgentResponse) GetAgentResponseDto() *components.AgentResponseDto {
	if a == nil {
		return nil
	}
	return a.AgentResponseDto
}

func (a *AgentsControllerUpdateAgentResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
