// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/v3/models/components"
)

type AgentsControllerCreateAgentRequest struct {
	NovuAnalyticsSource string `header:"style=simple,explode=false,name=Novu-Analytics-Source"`
	// A header for idempotency purposes
	IdempotencyKey        *string                          `header:"style=simple,explode=false,name=idempotency-key"`
	CreateAgentRequestDto components.CreateAgentRequestDto `request:"mediaType=application/json"`
}

func (a *AgentsControllerCreateAgentRequest) GetNovuAnalyticsSource() string {
	if a == nil {
		return ""
	}
	return a.NovuAnalyticsSource
}

func (a *AgentsControllerCreateAgentRequest) GetIdempotencyKey() *string {
	if a == nil {
		return nil
	}
	return a.IdempotencyKey
}

func (a *AgentsControllerCreateAgentRequest) GetCreateAgentRequestDto() components.CreateAgentRequestDto {
	if a == nil {
		return components.CreateAgentRequestDto{}
	}
	return a.CreateAgentRequestDto
}

type AgentsControllerCreateAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	AgentResponseDto *components.AgentResponseDto
	Headers          map[string][]string
}

func (a *AgentsControllerCreateAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AgentsControllerCreateAgentResponse) GetAgentResponseDto() *components.AgentResponseDto {
	if a == nil {
		return nil
	}
	return a.AgentResponseDto
}

func (a *AgentsControllerCreateAgentResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
