// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/novuhq/novu-go/v3/models/components"
)

// ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection - Direction of sorting
type ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection string

const (
	ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirectionAsc  ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection = "ASC"
	ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirectionDesc ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection = "DESC"
)

func (e ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection) ToPointer() *ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection {
	return &e
}
func (e *ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASC":
		fallthrough
	case "DESC":
		*e = ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection: %v", v)
	}
}

// ConnectionMode - Scope results relative to the subscriber. `subscriber` returns only the subscriber-owned connections, `shared` returns only shared (workspace-level) connections. Omit to return both.
type ConnectionMode string

const (
	ConnectionModeSubscriber ConnectionMode = "subscriber"
	ConnectionModeShared     ConnectionMode = "shared"
)

func (e ConnectionMode) ToPointer() *ConnectionMode {
	return &e
}
func (e *ConnectionMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "subscriber":
		fallthrough
	case "shared":
		*e = ConnectionMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionMode: %v", v)
	}
}

// Channel - Filter by channel type (email, sms, push, chat, etc.).
type Channel string

const (
	ChannelInApp Channel = "in_app"
	ChannelEmail Channel = "email"
	ChannelSms   Channel = "sms"
	ChannelChat  Channel = "chat"
	ChannelPush  Channel = "push"
	ChannelTool  Channel = "tool"
)

func (e Channel) ToPointer() *Channel {
	return &e
}
func (e *Channel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "in_app":
		fallthrough
	case "email":
		fallthrough
	case "sms":
		fallthrough
	case "chat":
		fallthrough
	case "push":
		fallthrough
	case "tool":
		*e = Channel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Channel: %v", v)
	}
}

type ChannelConnectionsControllerListChannelConnectionsRequest struct {
	// Cursor for pagination indicating the starting point after which to fetch results.
	After *string `queryParam:"style=form,explode=true,name=after"`
	// Cursor for pagination indicating the ending point before which to fetch results.
	Before *string `queryParam:"style=form,explode=true,name=before"`
	// Limit the number of items to return (max 100)
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Direction of sorting
	OrderDirection *ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection `queryParam:"style=form,explode=true,name=orderDirection"`
	// Field to order by
	OrderBy *string `queryParam:"style=form,explode=true,name=orderBy"`
	// Include cursor item in response
	IncludeCursor *bool `queryParam:"style=form,explode=true,name=includeCursor"`
	// The subscriber ID to filter results by
	SubscriberID *string `queryParam:"style=form,explode=true,name=subscriberId"`
	// Scope results relative to the subscriber. `subscriber` returns only the subscriber-owned connections, `shared` returns only shared (workspace-level) connections. Omit to return both.
	ConnectionMode *ConnectionMode `queryParam:"style=form,explode=true,name=connectionMode"`
	// Filter by channel type (email, sms, push, chat, etc.).
	Channel *Channel `queryParam:"style=form,explode=true,name=channel"`
	// Filter by provider identifier (e.g., sendgrid, twilio, slack, etc.).
	ProviderID *components.ProvidersIDEnum `queryParam:"style=form,explode=true,name=providerId"`
	// Filter by integration identifier.
	IntegrationIdentifier *string `queryParam:"style=form,explode=true,name=integrationIdentifier"`
	// Filter by exact context keys, order insensitive (format: "type:id")
	ContextKeys []string `queryParam:"style=form,explode=true,name=contextKeys"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetAfter() *string {
	if c == nil {
		return nil
	}
	return c.After
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetBefore() *string {
	if c == nil {
		return nil
	}
	return c.Before
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetLimit() *float64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetOrderDirection() *ChannelConnectionsControllerListChannelConnectionsQueryParamOrderDirection {
	if c == nil {
		return nil
	}
	return c.OrderDirection
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetOrderBy() *string {
	if c == nil {
		return nil
	}
	return c.OrderBy
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetIncludeCursor() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeCursor
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetSubscriberID() *string {
	if c == nil {
		return nil
	}
	return c.SubscriberID
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetConnectionMode() *ConnectionMode {
	if c == nil {
		return nil
	}
	return c.ConnectionMode
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetChannel() *Channel {
	if c == nil {
		return nil
	}
	return c.Channel
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetProviderID() *components.ProvidersIDEnum {
	if c == nil {
		return nil
	}
	return c.ProviderID
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetIntegrationIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.IntegrationIdentifier
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetContextKeys() []string {
	if c == nil {
		return nil
	}
	return c.ContextKeys
}

func (c *ChannelConnectionsControllerListChannelConnectionsRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

type ChannelConnectionsControllerListChannelConnectionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListChannelConnectionsResponseDto *components.ListChannelConnectionsResponseDto
	Headers                           map[string][]string
}

func (c *ChannelConnectionsControllerListChannelConnectionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ChannelConnectionsControllerListChannelConnectionsResponse) GetListChannelConnectionsResponseDto() *components.ListChannelConnectionsResponseDto {
	if c == nil {
		return nil
	}
	return c.ListChannelConnectionsResponseDto
}

func (c *ChannelConnectionsControllerListChannelConnectionsResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
