// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/v3/models/components"
)

type DomainsControllerUpdateDomainRequest struct {
	Domain string `pathParam:"style=simple,explode=false,name=domain"`
	// A header for idempotency purposes
	IdempotencyKey  *string                    `header:"style=simple,explode=false,name=idempotency-key"`
	UpdateDomainDto components.UpdateDomainDto `request:"mediaType=application/json"`
}

func (d *DomainsControllerUpdateDomainRequest) GetDomain() string {
	if d == nil {
		return ""
	}
	return d.Domain
}

func (d *DomainsControllerUpdateDomainRequest) GetIdempotencyKey() *string {
	if d == nil {
		return nil
	}
	return d.IdempotencyKey
}

func (d *DomainsControllerUpdateDomainRequest) GetUpdateDomainDto() components.UpdateDomainDto {
	if d == nil {
		return components.UpdateDomainDto{}
	}
	return d.UpdateDomainDto
}

type DomainsControllerUpdateDomainResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DomainResponseDto *components.DomainResponseDto
	Headers           map[string][]string
}

func (d *DomainsControllerUpdateDomainResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DomainsControllerUpdateDomainResponse) GetDomainResponseDto() *components.DomainResponseDto {
	if d == nil {
		return nil
	}
	return d.DomainResponseDto
}

func (d *DomainsControllerUpdateDomainResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
