// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/v3/models/components"
)

type EnvironmentsControllerPublishEnvironmentRequest struct {
	// Target environment ID (MongoDB ObjectId) to publish resources to
	TargetEnvironmentID string `pathParam:"style=simple,explode=false,name=targetEnvironmentId"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
	// Publish request configuration
	PublishEnvironmentRequestDto components.PublishEnvironmentRequestDto `request:"mediaType=application/json"`
}

func (e *EnvironmentsControllerPublishEnvironmentRequest) GetTargetEnvironmentID() string {
	if e == nil {
		return ""
	}
	return e.TargetEnvironmentID
}

func (e *EnvironmentsControllerPublishEnvironmentRequest) GetIdempotencyKey() *string {
	if e == nil {
		return nil
	}
	return e.IdempotencyKey
}

func (e *EnvironmentsControllerPublishEnvironmentRequest) GetPublishEnvironmentRequestDto() components.PublishEnvironmentRequestDto {
	if e == nil {
		return components.PublishEnvironmentRequestDto{}
	}
	return e.PublishEnvironmentRequestDto
}

type EnvironmentsControllerPublishEnvironmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PublishEnvironmentResponseDto *components.PublishEnvironmentResponseDto
	Headers                       map[string][]string
}

func (e *EnvironmentsControllerPublishEnvironmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EnvironmentsControllerPublishEnvironmentResponse) GetPublishEnvironmentResponseDto() *components.PublishEnvironmentResponseDto {
	if e == nil {
		return nil
	}
	return e.PublishEnvironmentResponseDto
}

func (e *EnvironmentsControllerPublishEnvironmentResponse) GetHeaders() map[string][]string {
	if e == nil {
		return map[string][]string{}
	}
	return e.Headers
}
