// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/v3/models/components"
)

type EnvironmentsControllerV1UpdateMyEnvironmentRequest struct {
	// The unique identifier of the environment
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environmentId"`
	// A header for idempotency purposes
	IdempotencyKey              *string                                `header:"style=simple,explode=false,name=idempotency-key"`
	UpdateEnvironmentRequestDto components.UpdateEnvironmentRequestDto `request:"mediaType=application/json"`
}

func (e *EnvironmentsControllerV1UpdateMyEnvironmentRequest) GetEnvironmentID() string {
	if e == nil {
		return ""
	}
	return e.EnvironmentID
}

func (e *EnvironmentsControllerV1UpdateMyEnvironmentRequest) GetIdempotencyKey() *string {
	if e == nil {
		return nil
	}
	return e.IdempotencyKey
}

func (e *EnvironmentsControllerV1UpdateMyEnvironmentRequest) GetUpdateEnvironmentRequestDto() components.UpdateEnvironmentRequestDto {
	if e == nil {
		return components.UpdateEnvironmentRequestDto{}
	}
	return e.UpdateEnvironmentRequestDto
}

type EnvironmentsControllerV1UpdateMyEnvironmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	EnvironmentResponseDto *components.EnvironmentResponseDto
	Headers                map[string][]string
}

func (e *EnvironmentsControllerV1UpdateMyEnvironmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EnvironmentsControllerV1UpdateMyEnvironmentResponse) GetEnvironmentResponseDto() *components.EnvironmentResponseDto {
	if e == nil {
		return nil
	}
	return e.EnvironmentResponseDto
}

func (e *EnvironmentsControllerV1UpdateMyEnvironmentResponse) GetHeaders() map[string][]string {
	if e == nil {
		return map[string][]string{}
	}
	return e.Headers
}
