// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type EventsControllerBroadcastEventToAllRequest struct {
	// A header for idempotency purposes
	IdempotencyKey              *string                                `header:"style=simple,explode=false,name=idempotency-key"`
	TriggerEventToAllRequestDto components.TriggerEventToAllRequestDto `request:"mediaType=application/json"`
}

func (e *EventsControllerBroadcastEventToAllRequest) GetIdempotencyKey() *string {
	if e == nil {
		return nil
	}
	return e.IdempotencyKey
}

func (e *EventsControllerBroadcastEventToAllRequest) GetTriggerEventToAllRequestDto() components.TriggerEventToAllRequestDto {
	if e == nil {
		return components.TriggerEventToAllRequestDto{}
	}
	return e.TriggerEventToAllRequestDto
}

type EventsControllerBroadcastEventToAllResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TriggerEventResponseDto *components.TriggerEventResponseDto
	Headers                 map[string][]string
}

func (e *EventsControllerBroadcastEventToAllResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EventsControllerBroadcastEventToAllResponse) GetTriggerEventResponseDto() *components.TriggerEventResponseDto {
	if e == nil {
		return nil
	}
	return e.TriggerEventResponseDto
}

func (e *EventsControllerBroadcastEventToAllResponse) GetHeaders() map[string][]string {
	if e == nil {
		return map[string][]string{}
	}
	return e.Headers
}
