// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type InboundWebhooksControllerHandleWebhookRequest struct {
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environmentId"`
	IntegrationID string `pathParam:"style=simple,explode=false,name=integrationId"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (i *InboundWebhooksControllerHandleWebhookRequest) GetEnvironmentID() string {
	if i == nil {
		return ""
	}
	return i.EnvironmentID
}

func (i *InboundWebhooksControllerHandleWebhookRequest) GetIntegrationID() string {
	if i == nil {
		return ""
	}
	return i.IntegrationID
}

func (i *InboundWebhooksControllerHandleWebhookRequest) GetIdempotencyKey() *string {
	if i == nil {
		return nil
	}
	return i.IdempotencyKey
}

type InboundWebhooksControllerHandleWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (i *InboundWebhooksControllerHandleWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}
