// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/novuhq/novu-go/models/components"
)

// QueryParamOrderDirection - Direction of sorting
type QueryParamOrderDirection string

const (
	QueryParamOrderDirectionAsc  QueryParamOrderDirection = "ASC"
	QueryParamOrderDirectionDesc QueryParamOrderDirection = "DESC"
)

func (e QueryParamOrderDirection) ToPointer() *QueryParamOrderDirection {
	return &e
}
func (e *QueryParamOrderDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASC":
		fallthrough
	case "DESC":
		*e = QueryParamOrderDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamOrderDirection: %v", v)
	}
}

type SubscribersControllerListSubscriberTopicsRequest struct {
	// The identifier of the subscriber
	SubscriberID string `pathParam:"style=simple,explode=false,name=subscriberId"`
	// Cursor for pagination indicating the starting point after which to fetch results.
	After *string `queryParam:"style=form,explode=true,name=after"`
	// Cursor for pagination indicating the ending point before which to fetch results.
	Before *string `queryParam:"style=form,explode=true,name=before"`
	// Limit the number of items to return (max 100)
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Direction of sorting
	OrderDirection *QueryParamOrderDirection `queryParam:"style=form,explode=true,name=orderDirection"`
	// Field to order by
	OrderBy *string `queryParam:"style=form,explode=true,name=orderBy"`
	// Include cursor item in response
	IncludeCursor *bool `queryParam:"style=form,explode=true,name=includeCursor"`
	// Filter by topic key
	Key *string `queryParam:"style=form,explode=true,name=key"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetSubscriberID() string {
	if s == nil {
		return ""
	}
	return s.SubscriberID
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetAfter() *string {
	if s == nil {
		return nil
	}
	return s.After
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetBefore() *string {
	if s == nil {
		return nil
	}
	return s.Before
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetLimit() *float64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetOrderDirection() *QueryParamOrderDirection {
	if s == nil {
		return nil
	}
	return s.OrderDirection
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetOrderBy() *string {
	if s == nil {
		return nil
	}
	return s.OrderBy
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetIncludeCursor() *bool {
	if s == nil {
		return nil
	}
	return s.IncludeCursor
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetKey() *string {
	if s == nil {
		return nil
	}
	return s.Key
}

func (s *SubscribersControllerListSubscriberTopicsRequest) GetIdempotencyKey() *string {
	if s == nil {
		return nil
	}
	return s.IdempotencyKey
}

type SubscribersControllerListSubscriberTopicsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListTopicSubscriptionsResponseDto *components.ListTopicSubscriptionsResponseDto
	Headers                           map[string][]string
}

func (s *SubscribersControllerListSubscriberTopicsResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SubscribersControllerListSubscriberTopicsResponse) GetListTopicSubscriptionsResponseDto() *components.ListTopicSubscriptionsResponseDto {
	if s == nil {
		return nil
	}
	return s.ListTopicSubscriptionsResponseDto
}

func (s *SubscribersControllerListSubscriberTopicsResponse) GetHeaders() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Headers
}
