// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type SubscribersV1ControllerCreateSubscriberRequest struct {
	// A header for idempotency purposes
	IdempotencyKey             *string                               `header:"style=simple,explode=false,name=idempotency-key"`
	CreateSubscriberRequestDto components.CreateSubscriberRequestDto `request:"mediaType=application/json"`
}

func (o *SubscribersV1ControllerCreateSubscriberRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *SubscribersV1ControllerCreateSubscriberRequest) GetCreateSubscriberRequestDto() components.CreateSubscriberRequestDto {
	if o == nil {
		return components.CreateSubscriberRequestDto{}
	}
	return o.CreateSubscriberRequestDto
}

type SubscribersV1ControllerCreateSubscriberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	SubscriberResponseDto *components.SubscriberResponseDto
	Headers               map[string][]string
}

func (o *SubscribersV1ControllerCreateSubscriberResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubscribersV1ControllerCreateSubscriberResponse) GetSubscriberResponseDto() *components.SubscriberResponseDto {
	if o == nil {
		return nil
	}
	return o.SubscriberResponseDto
}

func (o *SubscribersV1ControllerCreateSubscriberResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
