// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type SubscribersControllerGetSubscriberRequest struct {
	SubscriberID string `pathParam:"style=simple,explode=false,name=subscriberId"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (s *SubscribersControllerGetSubscriberRequest) GetSubscriberID() string {
	if s == nil {
		return ""
	}
	return s.SubscriberID
}

func (s *SubscribersControllerGetSubscriberRequest) GetIdempotencyKey() *string {
	if s == nil {
		return nil
	}
	return s.IdempotencyKey
}

type SubscribersControllerGetSubscriberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SubscriberResponseDto *components.SubscriberResponseDto
	Headers               map[string][]string
}

func (s *SubscribersControllerGetSubscriberResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SubscribersControllerGetSubscriberResponse) GetSubscriberResponseDto() *components.SubscriberResponseDto {
	if s == nil {
		return nil
	}
	return s.SubscriberResponseDto
}

func (s *SubscribersControllerGetSubscriberResponse) GetHeaders() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Headers
}
