// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type SubscribersControllerUpdateSubscriberOnlineFlagRequest struct {
	SubscriberID                         string                                          `pathParam:"style=simple,explode=false,name=subscriberId"`
	UpdateSubscriberOnlineFlagRequestDto components.UpdateSubscriberOnlineFlagRequestDto `request:"mediaType=application/json"`
}

func (o *SubscribersControllerUpdateSubscriberOnlineFlagRequest) GetSubscriberID() string {
	if o == nil {
		return ""
	}
	return o.SubscriberID
}

func (o *SubscribersControllerUpdateSubscriberOnlineFlagRequest) GetUpdateSubscriberOnlineFlagRequestDto() components.UpdateSubscriberOnlineFlagRequestDto {
	if o == nil {
		return components.UpdateSubscriberOnlineFlagRequestDto{}
	}
	return o.UpdateSubscriberOnlineFlagRequestDto
}

type SubscribersControllerUpdateSubscriberOnlineFlagResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SubscriberResponseDto *components.SubscriberResponseDto
	Headers               map[string][]string
}

func (o *SubscribersControllerUpdateSubscriberOnlineFlagResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubscribersControllerUpdateSubscriberOnlineFlagResponse) GetSubscriberResponseDto() *components.SubscriberResponseDto {
	if o == nil {
		return nil
	}
	return o.SubscriberResponseDto
}

func (o *SubscribersControllerUpdateSubscriberOnlineFlagResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
