// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/v3/models/components"
)

type SubscribersControllerArchiveAllNotificationsRequest struct {
	// The identifier of the subscriber
	SubscriberID string `pathParam:"style=simple,explode=false,name=subscriberId"`
	// A header for idempotency purposes
	IdempotencyKey                      *string                                        `header:"style=simple,explode=false,name=idempotency-key"`
	UpdateAllSubscriberNotificationsDto components.UpdateAllSubscriberNotificationsDto `request:"mediaType=application/json"`
}

func (s *SubscribersControllerArchiveAllNotificationsRequest) GetSubscriberID() string {
	if s == nil {
		return ""
	}
	return s.SubscriberID
}

func (s *SubscribersControllerArchiveAllNotificationsRequest) GetIdempotencyKey() *string {
	if s == nil {
		return nil
	}
	return s.IdempotencyKey
}

func (s *SubscribersControllerArchiveAllNotificationsRequest) GetUpdateAllSubscriberNotificationsDto() components.UpdateAllSubscriberNotificationsDto {
	if s == nil {
		return components.UpdateAllSubscriberNotificationsDto{}
	}
	return s.UpdateAllSubscriberNotificationsDto
}

type SubscribersControllerArchiveAllNotificationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (s *SubscribersControllerArchiveAllNotificationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SubscribersControllerArchiveAllNotificationsResponse) GetHeaders() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Headers
}
