// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/novuhq/novu-go/models/components"
)

type Criticality string

const (
	CriticalityCritical    Criticality = "critical"
	CriticalityNonCritical Criticality = "nonCritical"
	CriticalityAll         Criticality = "all"
)

func (e Criticality) ToPointer() *Criticality {
	return &e
}
func (e *Criticality) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "critical":
		fallthrough
	case "nonCritical":
		fallthrough
	case "all":
		*e = Criticality(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Criticality: %v", v)
	}
}

type SubscribersControllerGetSubscriberPreferencesRequest struct {
	SubscriberID string      `pathParam:"style=simple,explode=false,name=subscriberId"`
	Criticality  Criticality `queryParam:"style=form,explode=true,name=criticality"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (o *SubscribersControllerGetSubscriberPreferencesRequest) GetSubscriberID() string {
	if o == nil {
		return ""
	}
	return o.SubscriberID
}

func (o *SubscribersControllerGetSubscriberPreferencesRequest) GetCriticality() Criticality {
	if o == nil {
		return Criticality("")
	}
	return o.Criticality
}

func (o *SubscribersControllerGetSubscriberPreferencesRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

type SubscribersControllerGetSubscriberPreferencesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetSubscriberPreferencesDto *components.GetSubscriberPreferencesDto
	Headers                     map[string][]string
}

func (o *SubscribersControllerGetSubscriberPreferencesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubscribersControllerGetSubscriberPreferencesResponse) GetGetSubscriberPreferencesDto() *components.GetSubscriberPreferencesDto {
	if o == nil {
		return nil
	}
	return o.GetSubscriberPreferencesDto
}

func (o *SubscribersControllerGetSubscriberPreferencesResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
