// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type SubscribersControllerBulkUpdateSubscriberPreferencesRequest struct {
	SubscriberID string `pathParam:"style=simple,explode=false,name=subscriberId"`
	// A header for idempotency purposes
	IdempotencyKey                     *string                                       `header:"style=simple,explode=false,name=idempotency-key"`
	BulkUpdateSubscriberPreferencesDto components.BulkUpdateSubscriberPreferencesDto `request:"mediaType=application/json"`
}

func (o *SubscribersControllerBulkUpdateSubscriberPreferencesRequest) GetSubscriberID() string {
	if o == nil {
		return ""
	}
	return o.SubscriberID
}

func (o *SubscribersControllerBulkUpdateSubscriberPreferencesRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *SubscribersControllerBulkUpdateSubscriberPreferencesRequest) GetBulkUpdateSubscriberPreferencesDto() components.BulkUpdateSubscriberPreferencesDto {
	if o == nil {
		return components.BulkUpdateSubscriberPreferencesDto{}
	}
	return o.BulkUpdateSubscriberPreferencesDto
}

type SubscribersControllerBulkUpdateSubscriberPreferencesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetPreferencesResponseDtos []components.GetPreferencesResponseDto
	Headers                    map[string][]string
}

func (o *SubscribersControllerBulkUpdateSubscriberPreferencesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubscribersControllerBulkUpdateSubscriberPreferencesResponse) GetGetPreferencesResponseDtos() []components.GetPreferencesResponseDto {
	if o == nil {
		return nil
	}
	return o.GetPreferencesResponseDtos
}

func (o *SubscribersControllerBulkUpdateSubscriberPreferencesResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
