// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type SubscribersControllerMarkMessagesAsRequest struct {
	SubscriberID            string                             `pathParam:"style=simple,explode=false,name=subscriberId"`
	MessageMarkAsRequestDto components.MessageMarkAsRequestDto `request:"mediaType=application/json"`
}

func (o *SubscribersControllerMarkMessagesAsRequest) GetSubscriberID() string {
	if o == nil {
		return ""
	}
	return o.SubscriberID
}

func (o *SubscribersControllerMarkMessagesAsRequest) GetMessageMarkAsRequestDto() components.MessageMarkAsRequestDto {
	if o == nil {
		return components.MessageMarkAsRequestDto{}
	}
	return o.MessageMarkAsRequestDto
}

type SubscribersControllerMarkMessagesAsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	MessageResponseDtos []components.MessageResponseDto
	Headers             map[string][]string
}

func (o *SubscribersControllerMarkMessagesAsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubscribersControllerMarkMessagesAsResponse) GetMessageResponseDtos() []components.MessageResponseDto {
	if o == nil {
		return nil
	}
	return o.MessageResponseDtos
}

func (o *SubscribersControllerMarkMessagesAsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
