// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type SubscribersControllerGetSubscriberRequest struct {
	SubscriberID string `pathParam:"style=simple,explode=false,name=subscriberId"`
	// Includes the topics associated with the subscriber
	IncludeTopics *bool `queryParam:"style=form,explode=true,name=includeTopics"`
}

func (o *SubscribersControllerGetSubscriberRequest) GetSubscriberID() string {
	if o == nil {
		return ""
	}
	return o.SubscriberID
}

func (o *SubscribersControllerGetSubscriberRequest) GetIncludeTopics() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeTopics
}

type SubscribersControllerGetSubscriberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SubscriberResponseDto *components.SubscriberResponseDto
	Headers               map[string][]string
}

func (o *SubscribersControllerGetSubscriberResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubscribersControllerGetSubscriberResponse) GetSubscriberResponseDto() *components.SubscriberResponseDto {
	if o == nil {
		return nil
	}
	return o.SubscriberResponseDto
}

func (o *SubscribersControllerGetSubscriberResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
