// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type SubscribersV1ControllerChatOauthCallbackRequest struct {
	SubscriberID string `pathParam:"style=simple,explode=false,name=subscriberId"`
	ProviderID   any    `pathParam:"style=simple,explode=false,name=providerId"`
	// HMAC hash for the request
	HmacHash string `queryParam:"style=form,explode=true,name=hmacHash"`
	// The ID of the environment, must be a valid MongoDB ID
	EnvironmentID string `queryParam:"style=form,explode=true,name=environmentId"`
	// Optional integration identifier
	IntegrationIdentifier *string `queryParam:"style=form,explode=true,name=integrationIdentifier"`
	// Optional authorization code returned from the OAuth provider
	Code string `queryParam:"style=form,explode=true,name=code"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (o *SubscribersV1ControllerChatOauthCallbackRequest) GetSubscriberID() string {
	if o == nil {
		return ""
	}
	return o.SubscriberID
}

func (o *SubscribersV1ControllerChatOauthCallbackRequest) GetProviderID() any {
	if o == nil {
		return nil
	}
	return o.ProviderID
}

func (o *SubscribersV1ControllerChatOauthCallbackRequest) GetHmacHash() string {
	if o == nil {
		return ""
	}
	return o.HmacHash
}

func (o *SubscribersV1ControllerChatOauthCallbackRequest) GetEnvironmentID() string {
	if o == nil {
		return ""
	}
	return o.EnvironmentID
}

func (o *SubscribersV1ControllerChatOauthCallbackRequest) GetIntegrationIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.IntegrationIdentifier
}

func (o *SubscribersV1ControllerChatOauthCallbackRequest) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *SubscribersV1ControllerChatOauthCallbackRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

type SubscribersV1ControllerChatOauthCallbackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns plain text response.
	Res *string
	// Redirects to the specified URL.
	String  *string
	Headers map[string][]string
}

func (o *SubscribersV1ControllerChatOauthCallbackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubscribersV1ControllerChatOauthCallbackResponse) GetRes() *string {
	if o == nil {
		return nil
	}
	return o.Res
}

func (o *SubscribersV1ControllerChatOauthCallbackResponse) GetString() *string {
	if o == nil {
		return nil
	}
	return o.String
}

func (o *SubscribersV1ControllerChatOauthCallbackResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
