// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/v3/models/components"
)

type SubscribersControllerUnsnoozeNotificationRequest struct {
	// The identifier of the subscriber
	SubscriberID string `pathParam:"style=simple,explode=false,name=subscriberId"`
	// The identifier of the notification
	NotificationID string `pathParam:"style=simple,explode=false,name=notificationId"`
	// Context keys for filtering
	ContextKeys []string `queryParam:"style=form,explode=true,name=contextKeys"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (s *SubscribersControllerUnsnoozeNotificationRequest) GetSubscriberID() string {
	if s == nil {
		return ""
	}
	return s.SubscriberID
}

func (s *SubscribersControllerUnsnoozeNotificationRequest) GetNotificationID() string {
	if s == nil {
		return ""
	}
	return s.NotificationID
}

func (s *SubscribersControllerUnsnoozeNotificationRequest) GetContextKeys() []string {
	if s == nil {
		return nil
	}
	return s.ContextKeys
}

func (s *SubscribersControllerUnsnoozeNotificationRequest) GetIdempotencyKey() *string {
	if s == nil {
		return nil
	}
	return s.IdempotencyKey
}

type SubscribersControllerUnsnoozeNotificationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	InboxNotificationDto *components.InboxNotificationDto
	Headers              map[string][]string
}

func (s *SubscribersControllerUnsnoozeNotificationResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SubscribersControllerUnsnoozeNotificationResponse) GetInboxNotificationDto() *components.InboxNotificationDto {
	if s == nil {
		return nil
	}
	return s.InboxNotificationDto
}

func (s *SubscribersControllerUnsnoozeNotificationResponse) GetHeaders() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Headers
}
