// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type TopicsControllerGetTopicRequest struct {
	// The topic key
	TopicKey string `pathParam:"style=simple,explode=false,name=topicKey"`
}

func (o *TopicsControllerGetTopicRequest) GetTopicKey() string {
	if o == nil {
		return ""
	}
	return o.TopicKey
}

type TopicsControllerGetTopicResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetTopicResponseDto *components.GetTopicResponseDto
	Headers             map[string][]string
}

func (o *TopicsControllerGetTopicResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TopicsControllerGetTopicResponse) GetGetTopicResponseDto() *components.GetTopicResponseDto {
	if o == nil {
		return nil
	}
	return o.GetTopicResponseDto
}

func (o *TopicsControllerGetTopicResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
