// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type TranslationControllerCreateTranslationEndpointRequest struct {
	// A header for idempotency purposes
	IdempotencyKey              *string                                `header:"style=simple,explode=false,name=idempotency-key"`
	CreateTranslationRequestDto components.CreateTranslationRequestDto `request:"mediaType=application/json"`
}

func (t *TranslationControllerCreateTranslationEndpointRequest) GetIdempotencyKey() *string {
	if t == nil {
		return nil
	}
	return t.IdempotencyKey
}

func (t *TranslationControllerCreateTranslationEndpointRequest) GetCreateTranslationRequestDto() components.CreateTranslationRequestDto {
	if t == nil {
		return components.CreateTranslationRequestDto{}
	}
	return t.CreateTranslationRequestDto
}

type TranslationControllerCreateTranslationEndpointResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Translation created or updated successfully
	TranslationResponseDto *components.TranslationResponseDto
}

func (t *TranslationControllerCreateTranslationEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TranslationControllerCreateTranslationEndpointResponse) GetTranslationResponseDto() *components.TranslationResponseDto {
	if t == nil {
		return nil
	}
	return t.TranslationResponseDto
}
