// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/models/components"
)

type WorkflowControllerUpdateRequest struct {
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowId"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
	// Workflow update details
	UpdateWorkflowDto components.UpdateWorkflowDto `request:"mediaType=application/json"`
}

func (w *WorkflowControllerUpdateRequest) GetWorkflowID() string {
	if w == nil {
		return ""
	}
	return w.WorkflowID
}

func (w *WorkflowControllerUpdateRequest) GetIdempotencyKey() *string {
	if w == nil {
		return nil
	}
	return w.IdempotencyKey
}

func (w *WorkflowControllerUpdateRequest) GetUpdateWorkflowDto() components.UpdateWorkflowDto {
	if w == nil {
		return components.UpdateWorkflowDto{}
	}
	return w.UpdateWorkflowDto
}

type WorkflowControllerUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	WorkflowResponseDto *components.WorkflowResponseDto
	Headers             map[string][]string
}

func (w *WorkflowControllerUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkflowControllerUpdateResponse) GetWorkflowResponseDto() *components.WorkflowResponseDto {
	if w == nil {
		return nil
	}
	return w.WorkflowResponseDto
}

func (w *WorkflowControllerUpdateResponse) GetHeaders() map[string][]string {
	if w == nil {
		return map[string][]string{}
	}
	return w.Headers
}
