// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/novuhq/novu-go/v3/models/components"
)

type WorkflowControllerSyncRequest struct {
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowId"`
	// A header for idempotency purposes
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
	// Sync workflow details
	SyncWorkflowDto components.SyncWorkflowDto `request:"mediaType=application/json"`
}

func (w *WorkflowControllerSyncRequest) GetWorkflowID() string {
	if w == nil {
		return ""
	}
	return w.WorkflowID
}

func (w *WorkflowControllerSyncRequest) GetIdempotencyKey() *string {
	if w == nil {
		return nil
	}
	return w.IdempotencyKey
}

func (w *WorkflowControllerSyncRequest) GetSyncWorkflowDto() components.SyncWorkflowDto {
	if w == nil {
		return components.SyncWorkflowDto{}
	}
	return w.SyncWorkflowDto
}

type WorkflowControllerSyncResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	WorkflowResponseDto *components.WorkflowResponseDto
	Headers             map[string][]string
}

func (w *WorkflowControllerSyncResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkflowControllerSyncResponse) GetWorkflowResponseDto() *components.WorkflowResponseDto {
	if w == nil {
		return nil
	}
	return w.WorkflowResponseDto
}

func (w *WorkflowControllerSyncResponse) GetHeaders() map[string][]string {
	if w == nil {
		return map[string][]string{}
	}
	return w.Headers
}
