// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActorFeedItemDto struct {
	// The data associated with the actor, can be null if not applicable.
	Data *string `json:"data"`
	// The type of the actor, indicating the role in the notification process.
	Type ActorTypeEnum `json:"type"`
}

func (a *ActorFeedItemDto) GetData() *string {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *ActorFeedItemDto) GetType() ActorTypeEnum {
	if a == nil {
		return ActorTypeEnum("")
	}
	return a.Type
}
