// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BulkCreateSubscriberResponseDto struct {
	// An array of subscribers that were successfully updated.
	Updated []UpdatedSubscriberDto `json:"updated"`
	// An array of subscribers that were successfully created.
	Created []CreatedSubscriberDto `json:"created"`
	// An array of failed operations with error messages and optional subscriber IDs.
	Failed []FailedOperationDto `json:"failed"`
}

func (b *BulkCreateSubscriberResponseDto) GetUpdated() []UpdatedSubscriberDto {
	if b == nil {
		return []UpdatedSubscriberDto{}
	}
	return b.Updated
}

func (b *BulkCreateSubscriberResponseDto) GetCreated() []CreatedSubscriberDto {
	if b == nil {
		return []CreatedSubscriberDto{}
	}
	return b.Created
}

func (b *BulkCreateSubscriberResponseDto) GetFailed() []FailedOperationDto {
	if b == nil {
		return []FailedOperationDto{}
	}
	return b.Failed
}
