// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BulkUpdateSubscriberPreferencesDto struct {
	// Array of workflow preferences to update (maximum 100 items)
	Preferences []BulkUpdateSubscriberPreferenceItemDto `json:"preferences"`
}

func (b *BulkUpdateSubscriberPreferencesDto) GetPreferences() []BulkUpdateSubscriberPreferenceItemDto {
	if b == nil {
		return []BulkUpdateSubscriberPreferenceItemDto{}
	}
	return b.Preferences
}
