// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChannelSettingsDto struct {
	// The provider identifier for the credentials
	ProviderID ChatOrPushProviderEnum `json:"providerId"`
	// The integration identifier
	IntegrationIdentifier *string `json:"integrationIdentifier,omitempty"`
	// Credentials payload for the specified provider
	Credentials ChannelCredentials `json:"credentials"`
	// The unique identifier of the integration associated with this channel.
	IntegrationID string `json:"_integrationId"`
}

func (c *ChannelSettingsDto) GetProviderID() ChatOrPushProviderEnum {
	if c == nil {
		return ChatOrPushProviderEnum("")
	}
	return c.ProviderID
}

func (c *ChannelSettingsDto) GetIntegrationIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.IntegrationIdentifier
}

func (c *ChannelSettingsDto) GetCredentials() ChannelCredentials {
	if c == nil {
		return ChannelCredentials{}
	}
	return c.Credentials
}

func (c *ChannelSettingsDto) GetIntegrationID() string {
	if c == nil {
		return ""
	}
	return c.IntegrationID
}
