// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/novuhq/novu-go/v3/internal/utils"
)

// ChatControlDtoEditorType - Type of editor to use for the body. When omitted, inferred from the body: Maily JSON is "block", otherwise "text".
type ChatControlDtoEditorType string

const (
	ChatControlDtoEditorTypeBlock ChatControlDtoEditorType = "block"
	ChatControlDtoEditorTypeText  ChatControlDtoEditorType = "text"
)

func (e ChatControlDtoEditorType) ToPointer() *ChatControlDtoEditorType {
	return &e
}
func (e *ChatControlDtoEditorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "block":
		fallthrough
	case "text":
		*e = ChatControlDtoEditorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatControlDtoEditorType: %v", v)
	}
}

type ChatControlDto struct {
	// JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
	Skip map[string]any `json:"skip,omitempty"`
	// Content of the chat message.
	Body *string `json:"body,omitempty"`
	// Type of editor to use for the body. When omitted, inferred from the body: Maily JSON is "block", otherwise "text".
	EditorType *ChatControlDtoEditorType `json:"editorType,omitempty"`
}

func (c ChatControlDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatControlDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatControlDto) GetSkip() map[string]any {
	if c == nil {
		return nil
	}
	return c.Skip
}

func (c *ChatControlDto) GetBody() *string {
	if c == nil {
		return nil
	}
	return c.Body
}

func (c *ChatControlDto) GetEditorType() *ChatControlDtoEditorType {
	if c == nil {
		return nil
	}
	return c.EditorType
}
