// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/novuhq/novu-go/v3/internal/utils"
)

// ChatStepResponseDtoEditorType - Type of editor to use for the body. When omitted, inferred from the body: Maily JSON is "block", otherwise "text".
type ChatStepResponseDtoEditorType string

const (
	ChatStepResponseDtoEditorTypeBlock ChatStepResponseDtoEditorType = "block"
	ChatStepResponseDtoEditorTypeText  ChatStepResponseDtoEditorType = "text"
)

func (e ChatStepResponseDtoEditorType) ToPointer() *ChatStepResponseDtoEditorType {
	return &e
}
func (e *ChatStepResponseDtoEditorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "block":
		fallthrough
	case "text":
		*e = ChatStepResponseDtoEditorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatStepResponseDtoEditorType: %v", v)
	}
}

// ChatStepResponseDtoControlValues - Control values for the chat step
type ChatStepResponseDtoControlValues struct {
	// JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
	Skip map[string]any `json:"skip,omitempty"`
	// Content of the chat message.
	Body *string `json:"body,omitempty"`
	// Type of editor to use for the body. When omitted, inferred from the body: Maily JSON is "block", otherwise "text".
	EditorType           *ChatStepResponseDtoEditorType `json:"editorType,omitempty"`
	AdditionalProperties map[string]any                 `additionalProperties:"true" json:"-"`
}

func (c ChatStepResponseDtoControlValues) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatStepResponseDtoControlValues) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatStepResponseDtoControlValues) GetSkip() map[string]any {
	if c == nil {
		return nil
	}
	return c.Skip
}

func (c *ChatStepResponseDtoControlValues) GetBody() *string {
	if c == nil {
		return nil
	}
	return c.Body
}

func (c *ChatStepResponseDtoControlValues) GetEditorType() *ChatStepResponseDtoEditorType {
	if c == nil {
		return nil
	}
	return c.EditorType
}

func (c *ChatStepResponseDtoControlValues) GetAdditionalProperties() map[string]any {
	if c == nil {
		return nil
	}
	return c.AdditionalProperties
}

type ChatStepResponseDto struct {
	// Controls metadata for the chat step
	Controls ChatControlsMetadataResponseDto `json:"controls"`
	// Control values for the chat step
	ControlValues *ChatStepResponseDtoControlValues `json:"controlValues,omitempty"`
	// Per-provider content overrides keyed by providerId. Stored separately from controlValues and merged over the default body at send time. Keys are ChatProviderIdEnum / ToolProviderIdEnum values (e.g. `slack`, `whatsapp-business`, `pagerduty`).
	ProviderOverrides map[string]map[string]any `json:"providerOverrides,omitempty"`
	// JSON Schema for variables, follows the JSON Schema standard
	Variables map[string]any `json:"variables"`
	// Unique identifier of the step
	StepID string `json:"stepId"`
	// Database identifier of the step
	ID string `json:"_id"`
	// Name of the step
	Name string `json:"name"`
	// Slug of the step
	Slug string `json:"slug"`
	// Type of the step
	Type StepTypeEnum `json:"type"`
	// Origin of the layout
	Origin ResourceOriginEnum `json:"origin"`
	// Workflow identifier
	WorkflowID string `json:"workflowId"`
	// Workflow database identifier
	WorkflowDatabaseID string `json:"workflowDatabaseId"`
	// Issues associated with the step
	Issues *StepIssuesDto `json:"issues,omitempty"`
	// Hash identifying the deployed Cloudflare Worker for this step
	StepResolverHash *string `json:"stepResolverHash,omitempty"`
}

func (c ChatStepResponseDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatStepResponseDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"controls", "variables", "stepId", "_id", "name", "slug", "type", "origin", "workflowId", "workflowDatabaseId"}); err != nil {
		return err
	}
	return nil
}

func (c *ChatStepResponseDto) GetControls() ChatControlsMetadataResponseDto {
	if c == nil {
		return ChatControlsMetadataResponseDto{}
	}
	return c.Controls
}

func (c *ChatStepResponseDto) GetControlValues() *ChatStepResponseDtoControlValues {
	if c == nil {
		return nil
	}
	return c.ControlValues
}

func (c *ChatStepResponseDto) GetProviderOverrides() map[string]map[string]any {
	if c == nil {
		return nil
	}
	return c.ProviderOverrides
}

func (c *ChatStepResponseDto) GetVariables() map[string]any {
	if c == nil {
		return map[string]any{}
	}
	return c.Variables
}

func (c *ChatStepResponseDto) GetStepID() string {
	if c == nil {
		return ""
	}
	return c.StepID
}

func (c *ChatStepResponseDto) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChatStepResponseDto) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *ChatStepResponseDto) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

func (c *ChatStepResponseDto) GetType() StepTypeEnum {
	if c == nil {
		return StepTypeEnum("")
	}
	return c.Type
}

func (c *ChatStepResponseDto) GetOrigin() ResourceOriginEnum {
	if c == nil {
		return ResourceOriginEnum("")
	}
	return c.Origin
}

func (c *ChatStepResponseDto) GetWorkflowID() string {
	if c == nil {
		return ""
	}
	return c.WorkflowID
}

func (c *ChatStepResponseDto) GetWorkflowDatabaseID() string {
	if c == nil {
		return ""
	}
	return c.WorkflowDatabaseID
}

func (c *ChatStepResponseDto) GetIssues() *StepIssuesDto {
	if c == nil {
		return nil
	}
	return c.Issues
}

func (c *ChatStepResponseDto) GetStepResolverHash() *string {
	if c == nil {
		return nil
	}
	return c.StepResolverHash
}
