// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/novuhq/novu-go/v3/internal/utils"
)

// CreateOpsgenieIntegrationEndpointDtoContext2 - Rich context object with id and optional data
type CreateOpsgenieIntegrationEndpointDtoContext2 struct {
	ID string `json:"id"`
	// Optional additional context data
	Data map[string]any `json:"data,omitempty"`
}

func (c CreateOpsgenieIntegrationEndpointDtoContext2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOpsgenieIntegrationEndpointDtoContext2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateOpsgenieIntegrationEndpointDtoContext2) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateOpsgenieIntegrationEndpointDtoContext2) GetData() map[string]any {
	if c == nil {
		return nil
	}
	return c.Data
}

// #region class-body-createopsgenieintegrationendpointdtocontext2
// #endregion class-body-createopsgenieintegrationendpointdtocontext2

type CreateOpsgenieIntegrationEndpointDtoContextType string

const (
	CreateOpsgenieIntegrationEndpointDtoContextTypeStr                                          CreateOpsgenieIntegrationEndpointDtoContextType = "str"
	CreateOpsgenieIntegrationEndpointDtoContextTypeCreateOpsgenieIntegrationEndpointDtoContext2 CreateOpsgenieIntegrationEndpointDtoContextType = "CreateOpsgenieIntegrationEndpointDto_context_2"
)

type CreateOpsgenieIntegrationEndpointDtoContext struct {
	Str                                          *string                                       `queryParam:"inline" union:"member"`
	CreateOpsgenieIntegrationEndpointDtoContext2 *CreateOpsgenieIntegrationEndpointDtoContext2 `queryParam:"inline" union:"member"`

	Type CreateOpsgenieIntegrationEndpointDtoContextType
}

func CreateCreateOpsgenieIntegrationEndpointDtoContextStr(str string) CreateOpsgenieIntegrationEndpointDtoContext {
	typ := CreateOpsgenieIntegrationEndpointDtoContextTypeStr

	return CreateOpsgenieIntegrationEndpointDtoContext{
		Str:  &str,
		Type: typ,
	}
}

func CreateCreateOpsgenieIntegrationEndpointDtoContextCreateOpsgenieIntegrationEndpointDtoContext2(createOpsgenieIntegrationEndpointDtoContext2 CreateOpsgenieIntegrationEndpointDtoContext2) CreateOpsgenieIntegrationEndpointDtoContext {
	typ := CreateOpsgenieIntegrationEndpointDtoContextTypeCreateOpsgenieIntegrationEndpointDtoContext2

	return CreateOpsgenieIntegrationEndpointDtoContext{
		CreateOpsgenieIntegrationEndpointDtoContext2: &createOpsgenieIntegrationEndpointDtoContext2,
		Type: typ,
	}
}

func (u *CreateOpsgenieIntegrationEndpointDtoContext) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = CreateOpsgenieIntegrationEndpointDtoContext{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var createOpsgenieIntegrationEndpointDtoContext2 CreateOpsgenieIntegrationEndpointDtoContext2 = CreateOpsgenieIntegrationEndpointDtoContext2{}
	if err := utils.UnmarshalJSON(data, &createOpsgenieIntegrationEndpointDtoContext2, "", true, nil); err == nil {
		u.CreateOpsgenieIntegrationEndpointDtoContext2 = &createOpsgenieIntegrationEndpointDtoContext2
		u.Type = CreateOpsgenieIntegrationEndpointDtoContextTypeCreateOpsgenieIntegrationEndpointDtoContext2
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CreateOpsgenieIntegrationEndpointDtoContextTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateOpsgenieIntegrationEndpointDtoContext", string(data))
}

func (u CreateOpsgenieIntegrationEndpointDtoContext) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.CreateOpsgenieIntegrationEndpointDtoContext2 != nil {
		return utils.MarshalJSON(u.CreateOpsgenieIntegrationEndpointDtoContext2, "", true)
	}

	return nil, errors.New("could not marshal union type CreateOpsgenieIntegrationEndpointDtoContext: all fields are null")
}

// CreateOpsgenieIntegrationEndpointDtoType - Type of channel endpoint
type CreateOpsgenieIntegrationEndpointDtoType string

const (
	CreateOpsgenieIntegrationEndpointDtoTypeOpsgenieIntegration CreateOpsgenieIntegrationEndpointDtoType = "opsgenie_integration"
)

func (e CreateOpsgenieIntegrationEndpointDtoType) ToPointer() *CreateOpsgenieIntegrationEndpointDtoType {
	return &e
}
func (e *CreateOpsgenieIntegrationEndpointDtoType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "opsgenie_integration":
		*e = CreateOpsgenieIntegrationEndpointDtoType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateOpsgenieIntegrationEndpointDtoType: %v", v)
	}
}

type CreateOpsgenieIntegrationEndpointDto struct {
	// The unique identifier for the channel endpoint. If not provided, one will be generated automatically.
	Identifier *string `json:"identifier,omitempty"`
	// The subscriber ID to which the channel endpoint is linked
	SubscriberID string `json:"subscriberId"`
	// When true, the subscriber is created if it does not exist yet (existing subscribers are never modified). When false or omitted, an unknown subscriberId returns 404.
	CreateSubscriberIfMissing *bool                                                  `default:"false" json:"createSubscriberIfMissing"`
	Context                   map[string]CreateOpsgenieIntegrationEndpointDtoContext `json:"context,omitempty"`
	// The identifier of the integration to use for this channel endpoint.
	IntegrationIdentifier string `json:"integrationIdentifier"`
	// The identifier of the channel connection to use for this channel endpoint.
	ConnectionIdentifier *string `json:"connectionIdentifier,omitempty"`
	// Type of channel endpoint
	Type CreateOpsgenieIntegrationEndpointDtoType `json:"type"`
	// Opsgenie integration endpoint data. `apiKey` is encrypted at rest on the channel endpoint (`endpoint` field); `region` remains plaintext. No linked channel connection.
	Endpoint OpsgenieIntegrationEndpointDto `json:"endpoint"`
}

func (c CreateOpsgenieIntegrationEndpointDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOpsgenieIntegrationEndpointDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"subscriberId", "integrationIdentifier", "type", "endpoint"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateOpsgenieIntegrationEndpointDto) GetIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.Identifier
}

func (c *CreateOpsgenieIntegrationEndpointDto) GetSubscriberID() string {
	if c == nil {
		return ""
	}
	return c.SubscriberID
}

func (c *CreateOpsgenieIntegrationEndpointDto) GetCreateSubscriberIfMissing() *bool {
	if c == nil {
		return nil
	}
	return c.CreateSubscriberIfMissing
}

func (c *CreateOpsgenieIntegrationEndpointDto) GetContext() map[string]CreateOpsgenieIntegrationEndpointDtoContext {
	if c == nil {
		return nil
	}
	return c.Context
}

func (c *CreateOpsgenieIntegrationEndpointDto) GetIntegrationIdentifier() string {
	if c == nil {
		return ""
	}
	return c.IntegrationIdentifier
}

func (c *CreateOpsgenieIntegrationEndpointDto) GetConnectionIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.ConnectionIdentifier
}

func (c *CreateOpsgenieIntegrationEndpointDto) GetType() CreateOpsgenieIntegrationEndpointDtoType {
	if c == nil {
		return CreateOpsgenieIntegrationEndpointDtoType("")
	}
	return c.Type
}

func (c *CreateOpsgenieIntegrationEndpointDto) GetEndpoint() OpsgenieIntegrationEndpointDto {
	if c == nil {
		return OpsgenieIntegrationEndpointDto{}
	}
	return c.Endpoint
}
