// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/internal/utils"
)

type CreateLayoutDto struct {
	// Unique identifier for the layout
	LayoutID string `json:"layoutId"`
	// Name of the layout
	Name string `json:"name"`
	// Source of layout creation
	Source *LayoutCreationSourceEnum `default:"dashboard" json:"__source"`
}

func (c CreateLayoutDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateLayoutDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"layoutId", "name"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateLayoutDto) GetLayoutID() string {
	if c == nil {
		return ""
	}
	return c.LayoutID
}

func (c *CreateLayoutDto) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateLayoutDto) GetSource() *LayoutCreationSourceEnum {
	if c == nil {
		return nil
	}
	return c.Source
}
