// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/novuhq/novu-go/v3/internal/utils"
)

// CreateWebhookEndpointDtoContext2 - Rich context object with id and optional data
type CreateWebhookEndpointDtoContext2 struct {
	ID string `json:"id"`
	// Optional additional context data
	Data map[string]any `json:"data,omitempty"`
}

func (c CreateWebhookEndpointDtoContext2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWebhookEndpointDtoContext2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateWebhookEndpointDtoContext2) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateWebhookEndpointDtoContext2) GetData() map[string]any {
	if c == nil {
		return nil
	}
	return c.Data
}

// #region class-body-createwebhookendpointdtocontext2
// #endregion class-body-createwebhookendpointdtocontext2

type CreateWebhookEndpointDtoContextType string

const (
	CreateWebhookEndpointDtoContextTypeStr                              CreateWebhookEndpointDtoContextType = "str"
	CreateWebhookEndpointDtoContextTypeCreateWebhookEndpointDtoContext2 CreateWebhookEndpointDtoContextType = "CreateWebhookEndpointDto_context_2"
)

type CreateWebhookEndpointDtoContext struct {
	Str                              *string                           `queryParam:"inline" union:"member"`
	CreateWebhookEndpointDtoContext2 *CreateWebhookEndpointDtoContext2 `queryParam:"inline" union:"member"`

	Type CreateWebhookEndpointDtoContextType
}

func CreateCreateWebhookEndpointDtoContextStr(str string) CreateWebhookEndpointDtoContext {
	typ := CreateWebhookEndpointDtoContextTypeStr

	return CreateWebhookEndpointDtoContext{
		Str:  &str,
		Type: typ,
	}
}

func CreateCreateWebhookEndpointDtoContextCreateWebhookEndpointDtoContext2(createWebhookEndpointDtoContext2 CreateWebhookEndpointDtoContext2) CreateWebhookEndpointDtoContext {
	typ := CreateWebhookEndpointDtoContextTypeCreateWebhookEndpointDtoContext2

	return CreateWebhookEndpointDtoContext{
		CreateWebhookEndpointDtoContext2: &createWebhookEndpointDtoContext2,
		Type:                             typ,
	}
}

func (u *CreateWebhookEndpointDtoContext) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = CreateWebhookEndpointDtoContext{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var createWebhookEndpointDtoContext2 CreateWebhookEndpointDtoContext2 = CreateWebhookEndpointDtoContext2{}
	if err := utils.UnmarshalJSON(data, &createWebhookEndpointDtoContext2, "", true, nil); err == nil {
		u.CreateWebhookEndpointDtoContext2 = &createWebhookEndpointDtoContext2
		u.Type = CreateWebhookEndpointDtoContextTypeCreateWebhookEndpointDtoContext2
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CreateWebhookEndpointDtoContextTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateWebhookEndpointDtoContext", string(data))
}

func (u CreateWebhookEndpointDtoContext) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.CreateWebhookEndpointDtoContext2 != nil {
		return utils.MarshalJSON(u.CreateWebhookEndpointDtoContext2, "", true)
	}

	return nil, errors.New("could not marshal union type CreateWebhookEndpointDtoContext: all fields are null")
}

// CreateWebhookEndpointDtoType - Type of channel endpoint
type CreateWebhookEndpointDtoType string

const (
	CreateWebhookEndpointDtoTypeWebhook CreateWebhookEndpointDtoType = "webhook"
)

func (e CreateWebhookEndpointDtoType) ToPointer() *CreateWebhookEndpointDtoType {
	return &e
}
func (e *CreateWebhookEndpointDtoType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "webhook":
		*e = CreateWebhookEndpointDtoType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateWebhookEndpointDtoType: %v", v)
	}
}

type CreateWebhookEndpointDto struct {
	// The unique identifier for the channel endpoint. If not provided, one will be generated automatically.
	Identifier *string `json:"identifier,omitempty"`
	// The subscriber ID to which the channel endpoint is linked
	SubscriberID string `json:"subscriberId"`
	// When true, the subscriber is created if it does not exist yet (existing subscribers are never modified). When false or omitted, an unknown subscriberId returns 404.
	CreateSubscriberIfMissing *bool                                      `default:"false" json:"createSubscriberIfMissing"`
	Context                   map[string]CreateWebhookEndpointDtoContext `json:"context,omitempty"`
	// The identifier of the integration to use for this channel endpoint.
	IntegrationIdentifier string `json:"integrationIdentifier"`
	// The identifier of the channel connection to use for this channel endpoint.
	ConnectionIdentifier *string `json:"connectionIdentifier,omitempty"`
	// Type of channel endpoint
	Type CreateWebhookEndpointDtoType `json:"type"`
	// Webhook endpoint data
	Endpoint WebhookEndpointDto `json:"endpoint"`
}

func (c CreateWebhookEndpointDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWebhookEndpointDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"subscriberId", "integrationIdentifier", "type", "endpoint"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateWebhookEndpointDto) GetIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.Identifier
}

func (c *CreateWebhookEndpointDto) GetSubscriberID() string {
	if c == nil {
		return ""
	}
	return c.SubscriberID
}

func (c *CreateWebhookEndpointDto) GetCreateSubscriberIfMissing() *bool {
	if c == nil {
		return nil
	}
	return c.CreateSubscriberIfMissing
}

func (c *CreateWebhookEndpointDto) GetContext() map[string]CreateWebhookEndpointDtoContext {
	if c == nil {
		return nil
	}
	return c.Context
}

func (c *CreateWebhookEndpointDto) GetIntegrationIdentifier() string {
	if c == nil {
		return ""
	}
	return c.IntegrationIdentifier
}

func (c *CreateWebhookEndpointDto) GetConnectionIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.ConnectionIdentifier
}

func (c *CreateWebhookEndpointDto) GetType() CreateWebhookEndpointDtoType {
	if c == nil {
		return CreateWebhookEndpointDtoType("")
	}
	return c.Type
}

func (c *CreateWebhookEndpointDto) GetEndpoint() WebhookEndpointDto {
	if c == nil {
		return WebhookEndpointDto{}
	}
	return c.Endpoint
}
