// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DigestTimedConfigDtoWeekDays string

const (
	DigestTimedConfigDtoWeekDaysMonday    DigestTimedConfigDtoWeekDays = "monday"
	DigestTimedConfigDtoWeekDaysTuesday   DigestTimedConfigDtoWeekDays = "tuesday"
	DigestTimedConfigDtoWeekDaysWednesday DigestTimedConfigDtoWeekDays = "wednesday"
	DigestTimedConfigDtoWeekDaysThursday  DigestTimedConfigDtoWeekDays = "thursday"
	DigestTimedConfigDtoWeekDaysFriday    DigestTimedConfigDtoWeekDays = "friday"
	DigestTimedConfigDtoWeekDaysSaturday  DigestTimedConfigDtoWeekDays = "saturday"
	DigestTimedConfigDtoWeekDaysSunday    DigestTimedConfigDtoWeekDays = "sunday"
)

func (e DigestTimedConfigDtoWeekDays) ToPointer() *DigestTimedConfigDtoWeekDays {
	return &e
}
func (e *DigestTimedConfigDtoWeekDays) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "monday":
		fallthrough
	case "tuesday":
		fallthrough
	case "wednesday":
		fallthrough
	case "thursday":
		fallthrough
	case "friday":
		fallthrough
	case "saturday":
		fallthrough
	case "sunday":
		*e = DigestTimedConfigDtoWeekDays(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DigestTimedConfigDtoWeekDays: %v", v)
	}
}

type DigestTimedConfigDto struct {
	// Time at which the digest is triggered
	AtTime *string `json:"atTime,omitempty"`
	// Days of the week for the digest
	WeekDays []DigestTimedConfigDtoWeekDays `json:"weekDays,omitempty"`
	// Specific days of the month for the digest
	MonthDays []float64 `json:"monthDays,omitempty"`
	// Ordinal position for the digest
	Ordinal *OrdinalEnum `json:"ordinal,omitempty"`
	// Value of the ordinal
	OrdinalValue *OrdinalValueEnum `json:"ordinalValue,omitempty"`
	// Type of monthly schedule
	MonthlyType *MonthlyTypeEnum `json:"monthlyType,omitempty"`
	// Cron expression for scheduling
	CronExpression *string `json:"cronExpression,omitempty"`
}

func (d *DigestTimedConfigDto) GetAtTime() *string {
	if d == nil {
		return nil
	}
	return d.AtTime
}

func (d *DigestTimedConfigDto) GetWeekDays() []DigestTimedConfigDtoWeekDays {
	if d == nil {
		return nil
	}
	return d.WeekDays
}

func (d *DigestTimedConfigDto) GetMonthDays() []float64 {
	if d == nil {
		return nil
	}
	return d.MonthDays
}

func (d *DigestTimedConfigDto) GetOrdinal() *OrdinalEnum {
	if d == nil {
		return nil
	}
	return d.Ordinal
}

func (d *DigestTimedConfigDto) GetOrdinalValue() *OrdinalValueEnum {
	if d == nil {
		return nil
	}
	return d.OrdinalValue
}

func (d *DigestTimedConfigDto) GetMonthlyType() *MonthlyTypeEnum {
	if d == nil {
		return nil
	}
	return d.MonthlyType
}

func (d *DigestTimedConfigDto) GetCronExpression() *string {
	if d == nil {
		return nil
	}
	return d.CronExpression
}
