// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DomainRouteResponseDtoType string

const (
	DomainRouteResponseDtoTypeAgent   DomainRouteResponseDtoType = "agent"
	DomainRouteResponseDtoTypeWebhook DomainRouteResponseDtoType = "webhook"
)

func (e DomainRouteResponseDtoType) ToPointer() *DomainRouteResponseDtoType {
	return &e
}
func (e *DomainRouteResponseDtoType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent":
		fallthrough
	case "webhook":
		*e = DomainRouteResponseDtoType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DomainRouteResponseDtoType: %v", v)
	}
}

type DomainRouteResponseDto struct {
	ID       string `json:"_id"`
	DomainID string `json:"_domainId"`
	Address  string `json:"address"`
	// Internal id of the destination agent. Only present for agent routes.
	AgentID        *string                    `json:"agentId,omitempty"`
	Type           DomainRouteResponseDtoType `json:"type"`
	EnvironmentID  string                     `json:"_environmentId"`
	OrganizationID string                     `json:"_organizationId"`
	CreatedAt      string                     `json:"createdAt"`
	UpdatedAt      string                     `json:"updatedAt"`
	// String key-value metadata (max 10 keys, 500 characters total when set via API).
	Data map[string]string `json:"data,omitempty"`
}

func (d *DomainRouteResponseDto) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DomainRouteResponseDto) GetDomainID() string {
	if d == nil {
		return ""
	}
	return d.DomainID
}

func (d *DomainRouteResponseDto) GetAddress() string {
	if d == nil {
		return ""
	}
	return d.Address
}

func (d *DomainRouteResponseDto) GetAgentID() *string {
	if d == nil {
		return nil
	}
	return d.AgentID
}

func (d *DomainRouteResponseDto) GetType() DomainRouteResponseDtoType {
	if d == nil {
		return DomainRouteResponseDtoType("")
	}
	return d.Type
}

func (d *DomainRouteResponseDto) GetEnvironmentID() string {
	if d == nil {
		return ""
	}
	return d.EnvironmentID
}

func (d *DomainRouteResponseDto) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *DomainRouteResponseDto) GetCreatedAt() string {
	if d == nil {
		return ""
	}
	return d.CreatedAt
}

func (d *DomainRouteResponseDto) GetUpdatedAt() string {
	if d == nil {
		return ""
	}
	return d.UpdatedAt
}

func (d *DomainRouteResponseDto) GetData() map[string]string {
	if d == nil {
		return nil
	}
	return d.Data
}
