// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type EmailFromControlDto struct {
	// Sender email address override for this step.
	Email *string `json:"email,omitempty"`
	// Sender display name override for this step.
	Name *string `json:"name,omitempty"`
}

func (e EmailFromControlDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmailFromControlDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EmailFromControlDto) GetEmail() *string {
	if e == nil {
		return nil
	}
	return e.Email
}

func (e *EmailFromControlDto) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}
