// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/novuhq/novu-go/internal/utils"
)

// EmailStepResponseDtoEditorType - Type of editor to use for the body.
type EmailStepResponseDtoEditorType string

const (
	EmailStepResponseDtoEditorTypeBlock EmailStepResponseDtoEditorType = "block"
	EmailStepResponseDtoEditorTypeHTML  EmailStepResponseDtoEditorType = "html"
)

func (e EmailStepResponseDtoEditorType) ToPointer() *EmailStepResponseDtoEditorType {
	return &e
}
func (e *EmailStepResponseDtoEditorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "block":
		fallthrough
	case "html":
		*e = EmailStepResponseDtoEditorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EmailStepResponseDtoEditorType: %v", v)
	}
}

// EmailStepResponseDtoControlValues - Control values for the email step
type EmailStepResponseDtoControlValues struct {
	// JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
	Skip map[string]any `json:"skip,omitempty"`
	// Subject of the email.
	Subject string `json:"subject"`
	// Body content of the email, either a valid Maily JSON object, or html string.
	Body *string `default:"" json:"body"`
	// Type of editor to use for the body.
	EditorType *EmailStepResponseDtoEditorType `default:"block" json:"editorType"`
	// Disable sanitization of the output.
	DisableOutputSanitization *bool `default:"false" json:"disableOutputSanitization"`
	// Layout ID to use for the email. Null means no layout, undefined means default layout.
	LayoutID             *string        `json:"layoutId,omitempty"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (e EmailStepResponseDtoControlValues) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmailStepResponseDtoControlValues) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"subject"}); err != nil {
		return err
	}
	return nil
}

func (e *EmailStepResponseDtoControlValues) GetSkip() map[string]any {
	if e == nil {
		return nil
	}
	return e.Skip
}

func (e *EmailStepResponseDtoControlValues) GetSubject() string {
	if e == nil {
		return ""
	}
	return e.Subject
}

func (e *EmailStepResponseDtoControlValues) GetBody() *string {
	if e == nil {
		return nil
	}
	return e.Body
}

func (e *EmailStepResponseDtoControlValues) GetEditorType() *EmailStepResponseDtoEditorType {
	if e == nil {
		return nil
	}
	return e.EditorType
}

func (e *EmailStepResponseDtoControlValues) GetDisableOutputSanitization() *bool {
	if e == nil {
		return nil
	}
	return e.DisableOutputSanitization
}

func (e *EmailStepResponseDtoControlValues) GetLayoutID() *string {
	if e == nil {
		return nil
	}
	return e.LayoutID
}

func (e *EmailStepResponseDtoControlValues) GetAdditionalProperties() map[string]any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

type EmailStepResponseDto struct {
	// Controls metadata for the email step
	Controls EmailControlsMetadataResponseDto `json:"controls"`
	// Control values for the email step
	ControlValues *EmailStepResponseDtoControlValues `json:"controlValues,omitempty"`
	// JSON Schema for variables, follows the JSON Schema standard
	Variables map[string]any `json:"variables"`
	// Unique identifier of the step
	StepID string `json:"stepId"`
	// Database identifier of the step
	ID string `json:"_id"`
	// Name of the step
	Name string `json:"name"`
	// Slug of the step
	Slug string `json:"slug"`
	// Type of the step
	Type StepTypeEnum `json:"type"`
	// Origin of the layout
	Origin ResourceOriginEnum `json:"origin"`
	// Workflow identifier
	WorkflowID string `json:"workflowId"`
	// Workflow database identifier
	WorkflowDatabaseID string `json:"workflowDatabaseId"`
	// Issues associated with the step
	Issues *StepIssuesDto `json:"issues,omitempty"`
}

func (e EmailStepResponseDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmailStepResponseDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"controls", "variables", "stepId", "_id", "name", "slug", "type", "origin", "workflowId", "workflowDatabaseId"}); err != nil {
		return err
	}
	return nil
}

func (e *EmailStepResponseDto) GetControls() EmailControlsMetadataResponseDto {
	if e == nil {
		return EmailControlsMetadataResponseDto{}
	}
	return e.Controls
}

func (e *EmailStepResponseDto) GetControlValues() *EmailStepResponseDtoControlValues {
	if e == nil {
		return nil
	}
	return e.ControlValues
}

func (e *EmailStepResponseDto) GetVariables() map[string]any {
	if e == nil {
		return map[string]any{}
	}
	return e.Variables
}

func (e *EmailStepResponseDto) GetStepID() string {
	if e == nil {
		return ""
	}
	return e.StepID
}

func (e *EmailStepResponseDto) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EmailStepResponseDto) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EmailStepResponseDto) GetSlug() string {
	if e == nil {
		return ""
	}
	return e.Slug
}

func (e *EmailStepResponseDto) GetType() StepTypeEnum {
	if e == nil {
		return StepTypeEnum("")
	}
	return e.Type
}

func (e *EmailStepResponseDto) GetOrigin() ResourceOriginEnum {
	if e == nil {
		return ResourceOriginEnum("")
	}
	return e.Origin
}

func (e *EmailStepResponseDto) GetWorkflowID() string {
	if e == nil {
		return ""
	}
	return e.WorkflowID
}

func (e *EmailStepResponseDto) GetWorkflowDatabaseID() string {
	if e == nil {
		return ""
	}
	return e.WorkflowDatabaseID
}

func (e *EmailStepResponseDto) GetIssues() *StepIssuesDto {
	if e == nil {
		return nil
	}
	return e.Issues
}
