// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/internal/utils"
)

type EmailBlock struct {
	// Type of the email block
	Type EmailBlockTypeEnum `json:"type"`
	// Content of the email block
	Content string `json:"content"`
	// URL associated with the email block, if any
	URL *string `json:"url,omitempty"`
	// Styles applied to the email block
	Styles *EmailBlockStyles `json:"styles,omitempty"`
}

func (e EmailBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmailBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type", "content"}); err != nil {
		return err
	}
	return nil
}

func (e *EmailBlock) GetType() EmailBlockTypeEnum {
	if e == nil {
		return EmailBlockTypeEnum("")
	}
	return e.Type
}

func (e *EmailBlock) GetContent() string {
	if e == nil {
		return ""
	}
	return e.Content
}

func (e *EmailBlock) GetURL() *string {
	if e == nil {
		return nil
	}
	return e.URL
}

func (e *EmailBlock) GetStyles() *EmailBlockStyles {
	if e == nil {
		return nil
	}
	return e.Styles
}
