// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EmailChannelOverrides struct {
	// Override or remove the layout for all email steps in the workflow
	LayoutID *string `json:"layoutId,omitempty"`
}

func (o *EmailChannelOverrides) GetLayoutID() *string {
	if o == nil {
		return nil
	}
	return o.LayoutID
}
