// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EnvironmentVariableValueResponseDto struct {
	EnvironmentID string `json:"_environmentId"`
	// Value is masked (••••••••) for secret variables
	Value string `json:"value"`
}

func (e *EnvironmentVariableValueResponseDto) GetEnvironmentID() string {
	if e == nil {
		return ""
	}
	return e.EnvironmentID
}

func (e *EnvironmentVariableValueResponseDto) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}
