// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type FileRefDto struct {
	// Filename shown to the end user, including extension.
	Filename string `json:"filename"`
	// IANA MIME type of the file.
	MimeType *string `json:"mimeType,omitempty"`
	// Base64-encoded inline file bytes. Mutually exclusive with `url`. Decoded size must be ≤ 5 MB. Prefer `url` for larger files.
	Data *string `json:"data,omitempty"`
	// Publicly accessible HTTP(S) URL. Mutually exclusive with `data`. Server-side limits: 25 MB per file, 15 files per message, 50 MB aggregate.
	URL *string `json:"url,omitempty"`
}

func (f FileRefDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileRefDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"filename"}); err != nil {
		return err
	}
	return nil
}

func (f *FileRefDto) GetFilename() string {
	if f == nil {
		return ""
	}
	return f.Filename
}

func (f *FileRefDto) GetMimeType() *string {
	if f == nil {
		return nil
	}
	return f.MimeType
}

func (f *FileRefDto) GetData() *string {
	if f == nil {
		return nil
	}
	return f.Data
}

func (f *FileRefDto) GetURL() *string {
	if f == nil {
		return nil
	}
	return f.URL
}
