// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type GeneratePreviewResponseDtoResult9Type string

const (
	GeneratePreviewResponseDtoResult9TypeDigest GeneratePreviewResponseDtoResult9Type = "digest"
)

func (e GeneratePreviewResponseDtoResult9Type) ToPointer() *GeneratePreviewResponseDtoResult9Type {
	return &e
}
func (e *GeneratePreviewResponseDtoResult9Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "digest":
		*e = GeneratePreviewResponseDtoResult9Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GeneratePreviewResponseDtoResult9Type: %v", v)
	}
}

type Nine struct {
	Type    *GeneratePreviewResponseDtoResult9Type `json:"type,omitempty"`
	Preview *DigestRegularOutput                   `json:"preview,omitempty"`
}

func (n Nine) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *Nine) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *Nine) GetType() *GeneratePreviewResponseDtoResult9Type {
	if n == nil {
		return nil
	}
	return n.Type
}

func (n *Nine) GetPreview() *DigestRegularOutput {
	if n == nil {
		return nil
	}
	return n.Preview
}

type GeneratePreviewResponseDtoResult8Type string

const (
	GeneratePreviewResponseDtoResult8TypeDelay GeneratePreviewResponseDtoResult8Type = "delay"
)

func (e GeneratePreviewResponseDtoResult8Type) ToPointer() *GeneratePreviewResponseDtoResult8Type {
	return &e
}
func (e *GeneratePreviewResponseDtoResult8Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "delay":
		*e = GeneratePreviewResponseDtoResult8Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GeneratePreviewResponseDtoResult8Type: %v", v)
	}
}

type Eight struct {
	Type    *GeneratePreviewResponseDtoResult8Type `json:"type,omitempty"`
	Preview *DigestRegularOutput                   `json:"preview,omitempty"`
}

func (e Eight) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Eight) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Eight) GetType() *GeneratePreviewResponseDtoResult8Type {
	if e == nil {
		return nil
	}
	return e.Type
}

func (e *Eight) GetPreview() *DigestRegularOutput {
	if e == nil {
		return nil
	}
	return e.Preview
}

type GeneratePreviewResponseDtoResult7Type string

const (
	GeneratePreviewResponseDtoResult7TypeChat GeneratePreviewResponseDtoResult7Type = "chat"
)

func (e GeneratePreviewResponseDtoResult7Type) ToPointer() *GeneratePreviewResponseDtoResult7Type {
	return &e
}
func (e *GeneratePreviewResponseDtoResult7Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "chat":
		*e = GeneratePreviewResponseDtoResult7Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GeneratePreviewResponseDtoResult7Type: %v", v)
	}
}

type Seven struct {
	Type    *GeneratePreviewResponseDtoResult7Type `json:"type,omitempty"`
	Preview *ChatRenderOutput                      `json:"preview,omitempty"`
	Error   *PreviewErrorDto                       `json:"error,omitempty"`
}

func (s Seven) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Seven) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Seven) GetType() *GeneratePreviewResponseDtoResult7Type {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *Seven) GetPreview() *ChatRenderOutput {
	if s == nil {
		return nil
	}
	return s.Preview
}

func (s *Seven) GetError() *PreviewErrorDto {
	if s == nil {
		return nil
	}
	return s.Error
}

type GeneratePreviewResponseDtoResult6Type string

const (
	GeneratePreviewResponseDtoResult6TypePush GeneratePreviewResponseDtoResult6Type = "push"
)

func (e GeneratePreviewResponseDtoResult6Type) ToPointer() *GeneratePreviewResponseDtoResult6Type {
	return &e
}
func (e *GeneratePreviewResponseDtoResult6Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "push":
		*e = GeneratePreviewResponseDtoResult6Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GeneratePreviewResponseDtoResult6Type: %v", v)
	}
}

type Six struct {
	Type    *GeneratePreviewResponseDtoResult6Type `json:"type,omitempty"`
	Preview *PushRenderOutput                      `json:"preview,omitempty"`
	Error   *PreviewErrorDto                       `json:"error,omitempty"`
}

func (s Six) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Six) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Six) GetType() *GeneratePreviewResponseDtoResult6Type {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *Six) GetPreview() *PushRenderOutput {
	if s == nil {
		return nil
	}
	return s.Preview
}

func (s *Six) GetError() *PreviewErrorDto {
	if s == nil {
		return nil
	}
	return s.Error
}

type GeneratePreviewResponseDtoResult5Type string

const (
	GeneratePreviewResponseDtoResult5TypeSms GeneratePreviewResponseDtoResult5Type = "sms"
)

func (e GeneratePreviewResponseDtoResult5Type) ToPointer() *GeneratePreviewResponseDtoResult5Type {
	return &e
}
func (e *GeneratePreviewResponseDtoResult5Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sms":
		*e = GeneratePreviewResponseDtoResult5Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GeneratePreviewResponseDtoResult5Type: %v", v)
	}
}

type Result5 struct {
	Type    *GeneratePreviewResponseDtoResult5Type `json:"type,omitempty"`
	Preview *SmsRenderOutput                       `json:"preview,omitempty"`
	Error   *PreviewErrorDto                       `json:"error,omitempty"`
}

func (r Result5) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Result5) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Result5) GetType() *GeneratePreviewResponseDtoResult5Type {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *Result5) GetPreview() *SmsRenderOutput {
	if r == nil {
		return nil
	}
	return r.Preview
}

func (r *Result5) GetError() *PreviewErrorDto {
	if r == nil {
		return nil
	}
	return r.Error
}

// #region class-body-result5
// #endregion class-body-result5

type GeneratePreviewResponseDtoResult4Type string

const (
	GeneratePreviewResponseDtoResult4TypeInApp GeneratePreviewResponseDtoResult4Type = "in_app"
)

func (e GeneratePreviewResponseDtoResult4Type) ToPointer() *GeneratePreviewResponseDtoResult4Type {
	return &e
}
func (e *GeneratePreviewResponseDtoResult4Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "in_app":
		*e = GeneratePreviewResponseDtoResult4Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GeneratePreviewResponseDtoResult4Type: %v", v)
	}
}

type Result4 struct {
	Type    *GeneratePreviewResponseDtoResult4Type `json:"type,omitempty"`
	Preview *InAppRenderOutput                     `json:"preview,omitempty"`
	Error   *PreviewErrorDto                       `json:"error,omitempty"`
}

func (r Result4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Result4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Result4) GetType() *GeneratePreviewResponseDtoResult4Type {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *Result4) GetPreview() *InAppRenderOutput {
	if r == nil {
		return nil
	}
	return r.Preview
}

func (r *Result4) GetError() *PreviewErrorDto {
	if r == nil {
		return nil
	}
	return r.Error
}

// #region class-body-result4
// #endregion class-body-result4

type GeneratePreviewResponseDtoResult3Type string

const (
	GeneratePreviewResponseDtoResult3TypeEmail GeneratePreviewResponseDtoResult3Type = "email"
)

func (e GeneratePreviewResponseDtoResult3Type) ToPointer() *GeneratePreviewResponseDtoResult3Type {
	return &e
}
func (e *GeneratePreviewResponseDtoResult3Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "email":
		*e = GeneratePreviewResponseDtoResult3Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GeneratePreviewResponseDtoResult3Type: %v", v)
	}
}

type Three struct {
	Type    *GeneratePreviewResponseDtoResult3Type `json:"type,omitempty"`
	Preview *EmailRenderOutput                     `json:"preview,omitempty"`
	Error   *PreviewErrorDto                       `json:"error,omitempty"`
}

func (t Three) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Three) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Three) GetType() *GeneratePreviewResponseDtoResult3Type {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *Three) GetPreview() *EmailRenderOutput {
	if t == nil {
		return nil
	}
	return t.Preview
}

func (t *Three) GetError() *PreviewErrorDto {
	if t == nil {
		return nil
	}
	return t.Error
}

type GeneratePreviewResponseDtoResultType string

const (
	GeneratePreviewResponseDtoResultTypeEmail GeneratePreviewResponseDtoResultType = "email"
)

func (e GeneratePreviewResponseDtoResultType) ToPointer() *GeneratePreviewResponseDtoResultType {
	return &e
}
func (e *GeneratePreviewResponseDtoResultType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "email":
		*e = GeneratePreviewResponseDtoResultType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GeneratePreviewResponseDtoResultType: %v", v)
	}
}

type Result2 struct {
	Type    *GeneratePreviewResponseDtoResultType `json:"type,omitempty"`
	Preview *EmailRenderOutput                    `json:"preview,omitempty"`
	Error   *PreviewErrorDto                      `json:"error,omitempty"`
}

func (r Result2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Result2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Result2) GetType() *GeneratePreviewResponseDtoResultType {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *Result2) GetPreview() *EmailRenderOutput {
	if r == nil {
		return nil
	}
	return r.Preview
}

func (r *Result2) GetError() *PreviewErrorDto {
	if r == nil {
		return nil
	}
	return r.Error
}

// #region class-body-result2
// #endregion class-body-result2

type GeneratePreviewResponseDtoResultUnionType string

const (
	GeneratePreviewResponseDtoResultUnionTypeMapOfAny GeneratePreviewResponseDtoResultUnionType = "mapOfAny"
	GeneratePreviewResponseDtoResultUnionTypeResult2  GeneratePreviewResponseDtoResultUnionType = "result_2"
	GeneratePreviewResponseDtoResultUnionTypeThree    GeneratePreviewResponseDtoResultUnionType = "3"
	GeneratePreviewResponseDtoResultUnionTypeResult4  GeneratePreviewResponseDtoResultUnionType = "result_4"
	GeneratePreviewResponseDtoResultUnionTypeResult5  GeneratePreviewResponseDtoResultUnionType = "result_5"
	GeneratePreviewResponseDtoResultUnionTypeSix      GeneratePreviewResponseDtoResultUnionType = "6"
	GeneratePreviewResponseDtoResultUnionTypeSeven    GeneratePreviewResponseDtoResultUnionType = "7"
	GeneratePreviewResponseDtoResultUnionTypeEight    GeneratePreviewResponseDtoResultUnionType = "8"
	GeneratePreviewResponseDtoResultUnionTypeNine     GeneratePreviewResponseDtoResultUnionType = "9"
)

// GeneratePreviewResponseDtoResult - Preview result
type GeneratePreviewResponseDtoResult struct {
	MapOfAny map[string]any `queryParam:"inline" union:"member"`
	Result2  *Result2       `queryParam:"inline" union:"member"`
	Three    *Three         `queryParam:"inline" union:"member"`
	Result4  *Result4       `queryParam:"inline" union:"member"`
	Result5  *Result5       `queryParam:"inline" union:"member"`
	Six      *Six           `queryParam:"inline" union:"member"`
	Seven    *Seven         `queryParam:"inline" union:"member"`
	Eight    *Eight         `queryParam:"inline" union:"member"`
	Nine     *Nine          `queryParam:"inline" union:"member"`

	Type GeneratePreviewResponseDtoResultUnionType
}

func CreateGeneratePreviewResponseDtoResultMapOfAny(mapOfAny map[string]any) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeMapOfAny

	return GeneratePreviewResponseDtoResult{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateGeneratePreviewResponseDtoResultResult2(result2 Result2) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeResult2

	return GeneratePreviewResponseDtoResult{
		Result2: &result2,
		Type:    typ,
	}
}

func CreateGeneratePreviewResponseDtoResultThree(three Three) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeThree

	return GeneratePreviewResponseDtoResult{
		Three: &three,
		Type:  typ,
	}
}

func CreateGeneratePreviewResponseDtoResultResult4(result4 Result4) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeResult4

	return GeneratePreviewResponseDtoResult{
		Result4: &result4,
		Type:    typ,
	}
}

func CreateGeneratePreviewResponseDtoResultResult5(result5 Result5) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeResult5

	return GeneratePreviewResponseDtoResult{
		Result5: &result5,
		Type:    typ,
	}
}

func CreateGeneratePreviewResponseDtoResultSix(six Six) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeSix

	return GeneratePreviewResponseDtoResult{
		Six:  &six,
		Type: typ,
	}
}

func CreateGeneratePreviewResponseDtoResultSeven(seven Seven) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeSeven

	return GeneratePreviewResponseDtoResult{
		Seven: &seven,
		Type:  typ,
	}
}

func CreateGeneratePreviewResponseDtoResultEight(eight Eight) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeEight

	return GeneratePreviewResponseDtoResult{
		Eight: &eight,
		Type:  typ,
	}
}

func CreateGeneratePreviewResponseDtoResultNine(nine Nine) GeneratePreviewResponseDtoResult {
	typ := GeneratePreviewResponseDtoResultUnionTypeNine

	return GeneratePreviewResponseDtoResult{
		Nine: &nine,
		Type: typ,
	}
}

func (u *GeneratePreviewResponseDtoResult) UnmarshalJSON(data []byte) error {

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		u.MapOfAny = mapOfAny
		u.Type = GeneratePreviewResponseDtoResultUnionTypeMapOfAny
		return nil
	}

	var result2 Result2 = Result2{}
	if err := utils.UnmarshalJSON(data, &result2, "", true, nil); err == nil {
		u.Result2 = &result2
		u.Type = GeneratePreviewResponseDtoResultUnionTypeResult2
		return nil
	}

	var three Three = Three{}
	if err := utils.UnmarshalJSON(data, &three, "", true, nil); err == nil {
		u.Three = &three
		u.Type = GeneratePreviewResponseDtoResultUnionTypeThree
		return nil
	}

	var result4 Result4 = Result4{}
	if err := utils.UnmarshalJSON(data, &result4, "", true, nil); err == nil {
		u.Result4 = &result4
		u.Type = GeneratePreviewResponseDtoResultUnionTypeResult4
		return nil
	}

	var result5 Result5 = Result5{}
	if err := utils.UnmarshalJSON(data, &result5, "", true, nil); err == nil {
		u.Result5 = &result5
		u.Type = GeneratePreviewResponseDtoResultUnionTypeResult5
		return nil
	}

	var six Six = Six{}
	if err := utils.UnmarshalJSON(data, &six, "", true, nil); err == nil {
		u.Six = &six
		u.Type = GeneratePreviewResponseDtoResultUnionTypeSix
		return nil
	}

	var seven Seven = Seven{}
	if err := utils.UnmarshalJSON(data, &seven, "", true, nil); err == nil {
		u.Seven = &seven
		u.Type = GeneratePreviewResponseDtoResultUnionTypeSeven
		return nil
	}

	var eight Eight = Eight{}
	if err := utils.UnmarshalJSON(data, &eight, "", true, nil); err == nil {
		u.Eight = &eight
		u.Type = GeneratePreviewResponseDtoResultUnionTypeEight
		return nil
	}

	var nine Nine = Nine{}
	if err := utils.UnmarshalJSON(data, &nine, "", true, nil); err == nil {
		u.Nine = &nine
		u.Type = GeneratePreviewResponseDtoResultUnionTypeNine
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GeneratePreviewResponseDtoResult", string(data))
}

func (u GeneratePreviewResponseDtoResult) MarshalJSON() ([]byte, error) {
	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.Result2 != nil {
		return utils.MarshalJSON(u.Result2, "", true)
	}

	if u.Three != nil {
		return utils.MarshalJSON(u.Three, "", true)
	}

	if u.Result4 != nil {
		return utils.MarshalJSON(u.Result4, "", true)
	}

	if u.Result5 != nil {
		return utils.MarshalJSON(u.Result5, "", true)
	}

	if u.Six != nil {
		return utils.MarshalJSON(u.Six, "", true)
	}

	if u.Seven != nil {
		return utils.MarshalJSON(u.Seven, "", true)
	}

	if u.Eight != nil {
		return utils.MarshalJSON(u.Eight, "", true)
	}

	if u.Nine != nil {
		return utils.MarshalJSON(u.Nine, "", true)
	}

	return nil, errors.New("could not marshal union type GeneratePreviewResponseDtoResult: all fields are null")
}

type GeneratePreviewResponseDto struct {
	// Preview payload example
	PreviewPayloadExample PreviewPayloadDto `json:"previewPayloadExample"`
	// The payload schema that was used to generate the preview payload example
	Schema map[string]any `json:"schema,omitempty"`
	// Sample novu-signature header value for HTTP request steps
	NovuSignature *string `json:"novuSignature,omitempty"`
	// Preview result
	Result GeneratePreviewResponseDtoResult `json:"result"`
}

func (g *GeneratePreviewResponseDto) GetPreviewPayloadExample() PreviewPayloadDto {
	if g == nil {
		return PreviewPayloadDto{}
	}
	return g.PreviewPayloadExample
}

func (g *GeneratePreviewResponseDto) GetSchema() map[string]any {
	if g == nil {
		return nil
	}
	return g.Schema
}

func (g *GeneratePreviewResponseDto) GetNovuSignature() *string {
	if g == nil {
		return nil
	}
	return g.NovuSignature
}

func (g *GeneratePreviewResponseDto) GetResult() GeneratePreviewResponseDtoResult {
	if g == nil {
		return GeneratePreviewResponseDtoResult{}
	}
	return g.Result
}
