// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/novuhq/novu-go/v3/internal/utils"
)

// GetChannelEndpointResponseDtoChannel - The channel type (email, sms, push, chat, etc.).
type GetChannelEndpointResponseDtoChannel string

const (
	GetChannelEndpointResponseDtoChannelInApp GetChannelEndpointResponseDtoChannel = "in_app"
	GetChannelEndpointResponseDtoChannelEmail GetChannelEndpointResponseDtoChannel = "email"
	GetChannelEndpointResponseDtoChannelSms   GetChannelEndpointResponseDtoChannel = "sms"
	GetChannelEndpointResponseDtoChannelChat  GetChannelEndpointResponseDtoChannel = "chat"
	GetChannelEndpointResponseDtoChannelPush  GetChannelEndpointResponseDtoChannel = "push"
)

func (e GetChannelEndpointResponseDtoChannel) ToPointer() *GetChannelEndpointResponseDtoChannel {
	return &e
}
func (e *GetChannelEndpointResponseDtoChannel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "in_app":
		fallthrough
	case "email":
		fallthrough
	case "sms":
		fallthrough
	case "chat":
		fallthrough
	case "push":
		*e = GetChannelEndpointResponseDtoChannel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetChannelEndpointResponseDtoChannel: %v", v)
	}
}

// GetChannelEndpointResponseDtoProviderID - The provider identifier (e.g., sendgrid, twilio, slack, etc.).
type GetChannelEndpointResponseDtoProviderID string

const (
	GetChannelEndpointResponseDtoProviderIDEmailjs          GetChannelEndpointResponseDtoProviderID = "emailjs"
	GetChannelEndpointResponseDtoProviderIDMailgun          GetChannelEndpointResponseDtoProviderID = "mailgun"
	GetChannelEndpointResponseDtoProviderIDMailjet          GetChannelEndpointResponseDtoProviderID = "mailjet"
	GetChannelEndpointResponseDtoProviderIDMandrill         GetChannelEndpointResponseDtoProviderID = "mandrill"
	GetChannelEndpointResponseDtoProviderIDNodemailer       GetChannelEndpointResponseDtoProviderID = "nodemailer"
	GetChannelEndpointResponseDtoProviderIDPostmark         GetChannelEndpointResponseDtoProviderID = "postmark"
	GetChannelEndpointResponseDtoProviderIDSendgrid         GetChannelEndpointResponseDtoProviderID = "sendgrid"
	GetChannelEndpointResponseDtoProviderIDSendinblue       GetChannelEndpointResponseDtoProviderID = "sendinblue"
	GetChannelEndpointResponseDtoProviderIDSes              GetChannelEndpointResponseDtoProviderID = "ses"
	GetChannelEndpointResponseDtoProviderIDNetcore          GetChannelEndpointResponseDtoProviderID = "netcore"
	GetChannelEndpointResponseDtoProviderIDInfobipEmail     GetChannelEndpointResponseDtoProviderID = "infobip-email"
	GetChannelEndpointResponseDtoProviderIDResend           GetChannelEndpointResponseDtoProviderID = "resend"
	GetChannelEndpointResponseDtoProviderIDPlunk            GetChannelEndpointResponseDtoProviderID = "plunk"
	GetChannelEndpointResponseDtoProviderIDMailersend       GetChannelEndpointResponseDtoProviderID = "mailersend"
	GetChannelEndpointResponseDtoProviderIDMailtrap         GetChannelEndpointResponseDtoProviderID = "mailtrap"
	GetChannelEndpointResponseDtoProviderIDClickatell       GetChannelEndpointResponseDtoProviderID = "clickatell"
	GetChannelEndpointResponseDtoProviderIDOutlook365       GetChannelEndpointResponseDtoProviderID = "outlook365"
	GetChannelEndpointResponseDtoProviderIDNovuEmail        GetChannelEndpointResponseDtoProviderID = "novu-email"
	GetChannelEndpointResponseDtoProviderIDSparkpost        GetChannelEndpointResponseDtoProviderID = "sparkpost"
	GetChannelEndpointResponseDtoProviderIDEmailWebhook     GetChannelEndpointResponseDtoProviderID = "email-webhook"
	GetChannelEndpointResponseDtoProviderIDBraze            GetChannelEndpointResponseDtoProviderID = "braze"
	GetChannelEndpointResponseDtoProviderIDNexmo            GetChannelEndpointResponseDtoProviderID = "nexmo"
	GetChannelEndpointResponseDtoProviderIDPlivo            GetChannelEndpointResponseDtoProviderID = "plivo"
	GetChannelEndpointResponseDtoProviderIDSms77            GetChannelEndpointResponseDtoProviderID = "sms77"
	GetChannelEndpointResponseDtoProviderIDSmsCentral       GetChannelEndpointResponseDtoProviderID = "sms-central"
	GetChannelEndpointResponseDtoProviderIDSns              GetChannelEndpointResponseDtoProviderID = "sns"
	GetChannelEndpointResponseDtoProviderIDTelnyx           GetChannelEndpointResponseDtoProviderID = "telnyx"
	GetChannelEndpointResponseDtoProviderIDTwilio           GetChannelEndpointResponseDtoProviderID = "twilio"
	GetChannelEndpointResponseDtoProviderIDGupshup          GetChannelEndpointResponseDtoProviderID = "gupshup"
	GetChannelEndpointResponseDtoProviderIDFiretext         GetChannelEndpointResponseDtoProviderID = "firetext"
	GetChannelEndpointResponseDtoProviderIDInfobipSms       GetChannelEndpointResponseDtoProviderID = "infobip-sms"
	GetChannelEndpointResponseDtoProviderIDBurstSms         GetChannelEndpointResponseDtoProviderID = "burst-sms"
	GetChannelEndpointResponseDtoProviderIDBulkSms          GetChannelEndpointResponseDtoProviderID = "bulk-sms"
	GetChannelEndpointResponseDtoProviderIDIsendSms         GetChannelEndpointResponseDtoProviderID = "isend-sms"
	GetChannelEndpointResponseDtoProviderIDFortySixElks     GetChannelEndpointResponseDtoProviderID = "forty-six-elks"
	GetChannelEndpointResponseDtoProviderIDKannel           GetChannelEndpointResponseDtoProviderID = "kannel"
	GetChannelEndpointResponseDtoProviderIDMaqsam           GetChannelEndpointResponseDtoProviderID = "maqsam"
	GetChannelEndpointResponseDtoProviderIDTermii           GetChannelEndpointResponseDtoProviderID = "termii"
	GetChannelEndpointResponseDtoProviderIDAfricasTalking   GetChannelEndpointResponseDtoProviderID = "africas-talking"
	GetChannelEndpointResponseDtoProviderIDNovuSms          GetChannelEndpointResponseDtoProviderID = "novu-sms"
	GetChannelEndpointResponseDtoProviderIDSendchamp        GetChannelEndpointResponseDtoProviderID = "sendchamp"
	GetChannelEndpointResponseDtoProviderIDGenericSms       GetChannelEndpointResponseDtoProviderID = "generic-sms"
	GetChannelEndpointResponseDtoProviderIDClicksend        GetChannelEndpointResponseDtoProviderID = "clicksend"
	GetChannelEndpointResponseDtoProviderIDBandwidth        GetChannelEndpointResponseDtoProviderID = "bandwidth"
	GetChannelEndpointResponseDtoProviderIDMessagebird      GetChannelEndpointResponseDtoProviderID = "messagebird"
	GetChannelEndpointResponseDtoProviderIDSimpletexting    GetChannelEndpointResponseDtoProviderID = "simpletexting"
	GetChannelEndpointResponseDtoProviderIDAzureSms         GetChannelEndpointResponseDtoProviderID = "azure-sms"
	GetChannelEndpointResponseDtoProviderIDRingCentral      GetChannelEndpointResponseDtoProviderID = "ring-central"
	GetChannelEndpointResponseDtoProviderIDBrevoSms         GetChannelEndpointResponseDtoProviderID = "brevo-sms"
	GetChannelEndpointResponseDtoProviderIDEazySms          GetChannelEndpointResponseDtoProviderID = "eazy-sms"
	GetChannelEndpointResponseDtoProviderIDMobishastra      GetChannelEndpointResponseDtoProviderID = "mobishastra"
	GetChannelEndpointResponseDtoProviderIDAfroMessage      GetChannelEndpointResponseDtoProviderID = "afro-message"
	GetChannelEndpointResponseDtoProviderIDUnifonic         GetChannelEndpointResponseDtoProviderID = "unifonic"
	GetChannelEndpointResponseDtoProviderIDSmsmode          GetChannelEndpointResponseDtoProviderID = "smsmode"
	GetChannelEndpointResponseDtoProviderIDImedia           GetChannelEndpointResponseDtoProviderID = "imedia"
	GetChannelEndpointResponseDtoProviderIDSinch            GetChannelEndpointResponseDtoProviderID = "sinch"
	GetChannelEndpointResponseDtoProviderIDIsendproSms      GetChannelEndpointResponseDtoProviderID = "isendpro-sms"
	GetChannelEndpointResponseDtoProviderIDCmTelecom        GetChannelEndpointResponseDtoProviderID = "cm-telecom"
	GetChannelEndpointResponseDtoProviderIDFcm              GetChannelEndpointResponseDtoProviderID = "fcm"
	GetChannelEndpointResponseDtoProviderIDApns             GetChannelEndpointResponseDtoProviderID = "apns"
	GetChannelEndpointResponseDtoProviderIDExpo             GetChannelEndpointResponseDtoProviderID = "expo"
	GetChannelEndpointResponseDtoProviderIDOneSignal        GetChannelEndpointResponseDtoProviderID = "one-signal"
	GetChannelEndpointResponseDtoProviderIDPushpad          GetChannelEndpointResponseDtoProviderID = "pushpad"
	GetChannelEndpointResponseDtoProviderIDPushWebhook      GetChannelEndpointResponseDtoProviderID = "push-webhook"
	GetChannelEndpointResponseDtoProviderIDPusherBeams      GetChannelEndpointResponseDtoProviderID = "pusher-beams"
	GetChannelEndpointResponseDtoProviderIDAppio            GetChannelEndpointResponseDtoProviderID = "appio"
	GetChannelEndpointResponseDtoProviderIDNovu             GetChannelEndpointResponseDtoProviderID = "novu"
	GetChannelEndpointResponseDtoProviderIDSlack            GetChannelEndpointResponseDtoProviderID = "slack"
	GetChannelEndpointResponseDtoProviderIDDiscord          GetChannelEndpointResponseDtoProviderID = "discord"
	GetChannelEndpointResponseDtoProviderIDMsteams          GetChannelEndpointResponseDtoProviderID = "msteams"
	GetChannelEndpointResponseDtoProviderIDMattermost       GetChannelEndpointResponseDtoProviderID = "mattermost"
	GetChannelEndpointResponseDtoProviderIDRyver            GetChannelEndpointResponseDtoProviderID = "ryver"
	GetChannelEndpointResponseDtoProviderIDZulip            GetChannelEndpointResponseDtoProviderID = "zulip"
	GetChannelEndpointResponseDtoProviderIDGrafanaOnCall    GetChannelEndpointResponseDtoProviderID = "grafana-on-call"
	GetChannelEndpointResponseDtoProviderIDGetstream        GetChannelEndpointResponseDtoProviderID = "getstream"
	GetChannelEndpointResponseDtoProviderIDRocketChat       GetChannelEndpointResponseDtoProviderID = "rocket-chat"
	GetChannelEndpointResponseDtoProviderIDWhatsappBusiness GetChannelEndpointResponseDtoProviderID = "whatsapp-business"
	GetChannelEndpointResponseDtoProviderIDChatWebhook      GetChannelEndpointResponseDtoProviderID = "chat-webhook"
	GetChannelEndpointResponseDtoProviderIDNovuSlack        GetChannelEndpointResponseDtoProviderID = "novu-slack"
)

func (e GetChannelEndpointResponseDtoProviderID) ToPointer() *GetChannelEndpointResponseDtoProviderID {
	return &e
}
func (e *GetChannelEndpointResponseDtoProviderID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "emailjs":
		fallthrough
	case "mailgun":
		fallthrough
	case "mailjet":
		fallthrough
	case "mandrill":
		fallthrough
	case "nodemailer":
		fallthrough
	case "postmark":
		fallthrough
	case "sendgrid":
		fallthrough
	case "sendinblue":
		fallthrough
	case "ses":
		fallthrough
	case "netcore":
		fallthrough
	case "infobip-email":
		fallthrough
	case "resend":
		fallthrough
	case "plunk":
		fallthrough
	case "mailersend":
		fallthrough
	case "mailtrap":
		fallthrough
	case "clickatell":
		fallthrough
	case "outlook365":
		fallthrough
	case "novu-email":
		fallthrough
	case "sparkpost":
		fallthrough
	case "email-webhook":
		fallthrough
	case "braze":
		fallthrough
	case "nexmo":
		fallthrough
	case "plivo":
		fallthrough
	case "sms77":
		fallthrough
	case "sms-central":
		fallthrough
	case "sns":
		fallthrough
	case "telnyx":
		fallthrough
	case "twilio":
		fallthrough
	case "gupshup":
		fallthrough
	case "firetext":
		fallthrough
	case "infobip-sms":
		fallthrough
	case "burst-sms":
		fallthrough
	case "bulk-sms":
		fallthrough
	case "isend-sms":
		fallthrough
	case "forty-six-elks":
		fallthrough
	case "kannel":
		fallthrough
	case "maqsam":
		fallthrough
	case "termii":
		fallthrough
	case "africas-talking":
		fallthrough
	case "novu-sms":
		fallthrough
	case "sendchamp":
		fallthrough
	case "generic-sms":
		fallthrough
	case "clicksend":
		fallthrough
	case "bandwidth":
		fallthrough
	case "messagebird":
		fallthrough
	case "simpletexting":
		fallthrough
	case "azure-sms":
		fallthrough
	case "ring-central":
		fallthrough
	case "brevo-sms":
		fallthrough
	case "eazy-sms":
		fallthrough
	case "mobishastra":
		fallthrough
	case "afro-message":
		fallthrough
	case "unifonic":
		fallthrough
	case "smsmode":
		fallthrough
	case "imedia":
		fallthrough
	case "sinch":
		fallthrough
	case "isendpro-sms":
		fallthrough
	case "cm-telecom":
		fallthrough
	case "fcm":
		fallthrough
	case "apns":
		fallthrough
	case "expo":
		fallthrough
	case "one-signal":
		fallthrough
	case "pushpad":
		fallthrough
	case "push-webhook":
		fallthrough
	case "pusher-beams":
		fallthrough
	case "appio":
		fallthrough
	case "novu":
		fallthrough
	case "slack":
		fallthrough
	case "discord":
		fallthrough
	case "msteams":
		fallthrough
	case "mattermost":
		fallthrough
	case "ryver":
		fallthrough
	case "zulip":
		fallthrough
	case "grafana-on-call":
		fallthrough
	case "getstream":
		fallthrough
	case "rocket-chat":
		fallthrough
	case "whatsapp-business":
		fallthrough
	case "chat-webhook":
		fallthrough
	case "novu-slack":
		*e = GetChannelEndpointResponseDtoProviderID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetChannelEndpointResponseDtoProviderID: %v", v)
	}
}

// GetChannelEndpointResponseDtoType - Type of channel endpoint
type GetChannelEndpointResponseDtoType string

const (
	GetChannelEndpointResponseDtoTypeSlackChannel   GetChannelEndpointResponseDtoType = "slack_channel"
	GetChannelEndpointResponseDtoTypeSlackUser      GetChannelEndpointResponseDtoType = "slack_user"
	GetChannelEndpointResponseDtoTypeWebhook        GetChannelEndpointResponseDtoType = "webhook"
	GetChannelEndpointResponseDtoTypePhone          GetChannelEndpointResponseDtoType = "phone"
	GetChannelEndpointResponseDtoTypeMsTeamsChannel GetChannelEndpointResponseDtoType = "ms_teams_channel"
	GetChannelEndpointResponseDtoTypeMsTeamsUser    GetChannelEndpointResponseDtoType = "ms_teams_user"
)

func (e GetChannelEndpointResponseDtoType) ToPointer() *GetChannelEndpointResponseDtoType {
	return &e
}
func (e *GetChannelEndpointResponseDtoType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "slack_channel":
		fallthrough
	case "slack_user":
		fallthrough
	case "webhook":
		fallthrough
	case "phone":
		fallthrough
	case "ms_teams_channel":
		fallthrough
	case "ms_teams_user":
		*e = GetChannelEndpointResponseDtoType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetChannelEndpointResponseDtoType: %v", v)
	}
}

type EndpointType string

const (
	EndpointTypeSlackChannelEndpointDto EndpointType = "SlackChannelEndpointDto"
	EndpointTypeSlackUserEndpointDto    EndpointType = "SlackUserEndpointDto"
	EndpointTypeWebhookEndpointDto      EndpointType = "WebhookEndpointDto"
	EndpointTypePhoneEndpointDto        EndpointType = "PhoneEndpointDto"
)

// Endpoint data specific to the channel type
type Endpoint struct {
	SlackChannelEndpointDto *SlackChannelEndpointDto `queryParam:"inline" union:"member"`
	SlackUserEndpointDto    *SlackUserEndpointDto    `queryParam:"inline" union:"member"`
	WebhookEndpointDto      *WebhookEndpointDto      `queryParam:"inline" union:"member"`
	PhoneEndpointDto        *PhoneEndpointDto        `queryParam:"inline" union:"member"`

	Type EndpointType
}

func CreateEndpointSlackChannelEndpointDto(slackChannelEndpointDto SlackChannelEndpointDto) Endpoint {
	typ := EndpointTypeSlackChannelEndpointDto

	return Endpoint{
		SlackChannelEndpointDto: &slackChannelEndpointDto,
		Type:                    typ,
	}
}

func CreateEndpointSlackUserEndpointDto(slackUserEndpointDto SlackUserEndpointDto) Endpoint {
	typ := EndpointTypeSlackUserEndpointDto

	return Endpoint{
		SlackUserEndpointDto: &slackUserEndpointDto,
		Type:                 typ,
	}
}

func CreateEndpointWebhookEndpointDto(webhookEndpointDto WebhookEndpointDto) Endpoint {
	typ := EndpointTypeWebhookEndpointDto

	return Endpoint{
		WebhookEndpointDto: &webhookEndpointDto,
		Type:               typ,
	}
}

func CreateEndpointPhoneEndpointDto(phoneEndpointDto PhoneEndpointDto) Endpoint {
	typ := EndpointTypePhoneEndpointDto

	return Endpoint{
		PhoneEndpointDto: &phoneEndpointDto,
		Type:             typ,
	}
}

func (u *Endpoint) UnmarshalJSON(data []byte) error {

	var slackChannelEndpointDto SlackChannelEndpointDto = SlackChannelEndpointDto{}
	if err := utils.UnmarshalJSON(data, &slackChannelEndpointDto, "", true, nil); err == nil {
		u.SlackChannelEndpointDto = &slackChannelEndpointDto
		u.Type = EndpointTypeSlackChannelEndpointDto
		return nil
	}

	var slackUserEndpointDto SlackUserEndpointDto = SlackUserEndpointDto{}
	if err := utils.UnmarshalJSON(data, &slackUserEndpointDto, "", true, nil); err == nil {
		u.SlackUserEndpointDto = &slackUserEndpointDto
		u.Type = EndpointTypeSlackUserEndpointDto
		return nil
	}

	var webhookEndpointDto WebhookEndpointDto = WebhookEndpointDto{}
	if err := utils.UnmarshalJSON(data, &webhookEndpointDto, "", true, nil); err == nil {
		u.WebhookEndpointDto = &webhookEndpointDto
		u.Type = EndpointTypeWebhookEndpointDto
		return nil
	}

	var phoneEndpointDto PhoneEndpointDto = PhoneEndpointDto{}
	if err := utils.UnmarshalJSON(data, &phoneEndpointDto, "", true, nil); err == nil {
		u.PhoneEndpointDto = &phoneEndpointDto
		u.Type = EndpointTypePhoneEndpointDto
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Endpoint", string(data))
}

func (u Endpoint) MarshalJSON() ([]byte, error) {
	if u.SlackChannelEndpointDto != nil {
		return utils.MarshalJSON(u.SlackChannelEndpointDto, "", true)
	}

	if u.SlackUserEndpointDto != nil {
		return utils.MarshalJSON(u.SlackUserEndpointDto, "", true)
	}

	if u.WebhookEndpointDto != nil {
		return utils.MarshalJSON(u.WebhookEndpointDto, "", true)
	}

	if u.PhoneEndpointDto != nil {
		return utils.MarshalJSON(u.PhoneEndpointDto, "", true)
	}

	return nil, errors.New("could not marshal union type Endpoint: all fields are null")
}

type GetChannelEndpointResponseDto struct {
	// The unique identifier of the channel endpoint.
	Identifier string `json:"identifier"`
	// The channel type (email, sms, push, chat, etc.).
	Channel *GetChannelEndpointResponseDtoChannel `json:"channel"`
	// The provider identifier (e.g., sendgrid, twilio, slack, etc.).
	ProviderID *GetChannelEndpointResponseDtoProviderID `json:"providerId"`
	// The identifier of the integration to use for this channel endpoint.
	IntegrationIdentifier *string `json:"integrationIdentifier"`
	// The identifier of the channel connection used for this endpoint.
	ConnectionIdentifier *string `json:"connectionIdentifier"`
	// The subscriber ID to which the channel endpoint is linked
	SubscriberID *string `json:"subscriberId"`
	// The context of the channel connection
	ContextKeys []string `json:"contextKeys"`
	// Type of channel endpoint
	Type GetChannelEndpointResponseDtoType `json:"type"`
	// Endpoint data specific to the channel type
	Endpoint Endpoint `json:"endpoint"`
	// The timestamp indicating when the channel endpoint was created, in ISO 8601 format.
	CreatedAt string `json:"createdAt"`
	// The timestamp indicating when the channel endpoint was last updated, in ISO 8601 format.
	UpdatedAt string `json:"updatedAt"`
}

func (g *GetChannelEndpointResponseDto) GetIdentifier() string {
	if g == nil {
		return ""
	}
	return g.Identifier
}

func (g *GetChannelEndpointResponseDto) GetChannel() *GetChannelEndpointResponseDtoChannel {
	if g == nil {
		return nil
	}
	return g.Channel
}

func (g *GetChannelEndpointResponseDto) GetProviderID() *GetChannelEndpointResponseDtoProviderID {
	if g == nil {
		return nil
	}
	return g.ProviderID
}

func (g *GetChannelEndpointResponseDto) GetIntegrationIdentifier() *string {
	if g == nil {
		return nil
	}
	return g.IntegrationIdentifier
}

func (g *GetChannelEndpointResponseDto) GetConnectionIdentifier() *string {
	if g == nil {
		return nil
	}
	return g.ConnectionIdentifier
}

func (g *GetChannelEndpointResponseDto) GetSubscriberID() *string {
	if g == nil {
		return nil
	}
	return g.SubscriberID
}

func (g *GetChannelEndpointResponseDto) GetContextKeys() []string {
	if g == nil {
		return []string{}
	}
	return g.ContextKeys
}

func (g *GetChannelEndpointResponseDto) GetType() GetChannelEndpointResponseDtoType {
	if g == nil {
		return GetChannelEndpointResponseDtoType("")
	}
	return g.Type
}

func (g *GetChannelEndpointResponseDto) GetEndpoint() Endpoint {
	if g == nil {
		return Endpoint{}
	}
	return g.Endpoint
}

func (g *GetChannelEndpointResponseDto) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetChannelEndpointResponseDto) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}
