// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetPreferencesResponseDtoData - Custom data associated with the workflow
type GetPreferencesResponseDtoData struct {
}

// Workflow information if this is a template-level preference
type Workflow struct {
	// Unique identifier of the workflow
	ID string `json:"id"`
	// Workflow identifier used for triggering
	Identifier string `json:"identifier"`
	// Human-readable name of the workflow
	Name string `json:"name"`
	// Whether this workflow is marked as critical
	Critical bool `json:"critical"`
	// Tags associated with the workflow
	Tags []string `json:"tags,omitempty"`
	// Custom data associated with the workflow
	Data *GetPreferencesResponseDtoData `json:"data,omitempty"`
	// Severity of the workflow
	Severity SeverityLevelEnum `json:"severity"`
}

func (w *Workflow) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *Workflow) GetIdentifier() string {
	if w == nil {
		return ""
	}
	return w.Identifier
}

func (w *Workflow) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *Workflow) GetCritical() bool {
	if w == nil {
		return false
	}
	return w.Critical
}

func (w *Workflow) GetTags() []string {
	if w == nil {
		return nil
	}
	return w.Tags
}

func (w *Workflow) GetData() *GetPreferencesResponseDtoData {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *Workflow) GetSeverity() SeverityLevelEnum {
	if w == nil {
		return SeverityLevelEnum("")
	}
	return w.Severity
}

type GetPreferencesResponseDto struct {
	// The level of the preference (global or template)
	Level PreferenceLevelEnum `json:"level"`
	// Workflow information if this is a template-level preference
	Workflow *Workflow `json:"workflow,omitempty"`
	// Whether the preference is enabled
	Enabled bool `json:"enabled"`
	// Channel-specific preference settings
	Channels SubscriberPreferenceChannels `json:"channels"`
}

func (g *GetPreferencesResponseDto) GetLevel() PreferenceLevelEnum {
	if g == nil {
		return PreferenceLevelEnum("")
	}
	return g.Level
}

func (g *GetPreferencesResponseDto) GetWorkflow() *Workflow {
	if g == nil {
		return nil
	}
	return g.Workflow
}

func (g *GetPreferencesResponseDto) GetEnabled() bool {
	if g == nil {
		return false
	}
	return g.Enabled
}

func (g *GetPreferencesResponseDto) GetChannels() SubscriberPreferenceChannels {
	if g == nil {
		return SubscriberPreferenceChannels{}
	}
	return g.Channels
}
