// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetSubscriberNotificationsCountResponseDto struct {
	// The count of notifications matching the filter
	Count float64 `json:"count"`
	// The filter applied
	Filter map[string]any `json:"filter"`
}

func (g *GetSubscriberNotificationsCountResponseDto) GetCount() float64 {
	if g == nil {
		return 0.0
	}
	return g.Count
}

func (g *GetSubscriberNotificationsCountResponseDto) GetFilter() map[string]any {
	if g == nil {
		return map[string]any{}
	}
	return g.Filter
}
