// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type HTTPRequestKeyValuePairDto struct {
	// Key of the key-value pair
	Key string `json:"key"`
	// Value of the key-value pair
	Value string `json:"value"`
}

func (h HTTPRequestKeyValuePairDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HTTPRequestKeyValuePairDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, []string{"key", "value"}); err != nil {
		return err
	}
	return nil
}

func (h *HTTPRequestKeyValuePairDto) GetKey() string {
	if h == nil {
		return ""
	}
	return h.Key
}

func (h *HTTPRequestKeyValuePairDto) GetValue() string {
	if h == nil {
		return ""
	}
	return h.Value
}
