// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InboxActionDto struct {
	// Label of the action button
	Label string `json:"label"`
	// Whether the action has been completed
	IsCompleted bool `json:"isCompleted"`
	// Redirect configuration for the action
	Redirect *RedirectDto `json:"redirect,omitempty"`
}

func (i *InboxActionDto) GetLabel() string {
	if i == nil {
		return ""
	}
	return i.Label
}

func (i *InboxActionDto) GetIsCompleted() bool {
	if i == nil {
		return false
	}
	return i.IsCompleted
}

func (i *InboxActionDto) GetRedirect() *RedirectDto {
	if i == nil {
		return nil
	}
	return i.Redirect
}
