// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LayoutPreviewPayloadDto struct {
	// Partial subscriber information
	Subscriber *SubscriberResponseDtoOptional `json:"subscriber,omitempty"`
}

func (l *LayoutPreviewPayloadDto) GetSubscriber() *SubscriberResponseDtoOptional {
	if l == nil {
		return nil
	}
	return l.Subscriber
}
