// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkChannelEndpointResponseDto struct {
	// URL the subscriber opens to link their chat identity (OAuth URL or deep link)
	URL string `json:"url"`
	// Provider-specific metadata returned alongside the link URL
	ProviderMetadata map[string]any `json:"providerMetadata,omitempty"`
}

func (l *LinkChannelEndpointResponseDto) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *LinkChannelEndpointResponseDto) GetProviderMetadata() map[string]any {
	if l == nil {
		return nil
	}
	return l.ProviderMetadata
}
