// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type MarkdownReplyContentDto struct {
	// Plain text or markdown body. Converted to the platform-native format by Novu.
	Markdown string `json:"markdown"`
	// Optional attachments (max 15). Each file needs exactly one of data or url.
	Files []FileRefDto `json:"files,omitempty"`
}

func (m MarkdownReplyContentDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MarkdownReplyContentDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"markdown"}); err != nil {
		return err
	}
	return nil
}

func (m *MarkdownReplyContentDto) GetMarkdown() string {
	if m == nil {
		return ""
	}
	return m.Markdown
}

func (m *MarkdownReplyContentDto) GetFiles() []FileRefDto {
	if m == nil {
		return nil
	}
	return m.Files
}
