// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type MsTeamsUserEndpointDto struct {
	// MS Teams user ID
	UserID string `json:"userId"`
}

func (m MsTeamsUserEndpointDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MsTeamsUserEndpointDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"userId"}); err != nil {
		return err
	}
	return nil
}

func (m *MsTeamsUserEndpointDto) GetUserID() string {
	if m == nil {
		return ""
	}
	return m.UserID
}
