// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PatchWorkflowDto struct {
	// Activate or deactivate the workflow
	Active *bool `json:"active,omitempty"`
	// New name for the workflow
	Name *string `json:"name,omitempty"`
	// Updated description of the workflow
	Description *string `json:"description,omitempty"`
	// Tags associated with the workflow
	Tags []string `json:"tags,omitempty"`
	// The payload JSON Schema for the workflow
	PayloadSchema map[string]any `json:"payloadSchema,omitempty"`
	// Enable or disable payload schema validation
	ValidatePayload *bool `json:"validatePayload,omitempty"`
	// Enable or disable translations for this workflow
	IsTranslationEnabled *bool `json:"isTranslationEnabled,omitempty"`
}

func (p *PatchWorkflowDto) GetActive() *bool {
	if p == nil {
		return nil
	}
	return p.Active
}

func (p *PatchWorkflowDto) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PatchWorkflowDto) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PatchWorkflowDto) GetTags() []string {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *PatchWorkflowDto) GetPayloadSchema() map[string]any {
	if p == nil {
		return nil
	}
	return p.PayloadSchema
}

func (p *PatchWorkflowDto) GetValidatePayload() *bool {
	if p == nil {
		return nil
	}
	return p.ValidatePayload
}

func (p *PatchWorkflowDto) GetIsTranslationEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.IsTranslationEnabled
}
