// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PatchSubscriberRequestDto struct {
	// First name of the subscriber
	FirstName *string `json:"firstName,omitempty"`
	// Last name of the subscriber
	LastName *string `json:"lastName,omitempty"`
	// Email address of the subscriber
	Email *string `json:"email,omitempty"`
	// Phone number of the subscriber
	Phone *string `json:"phone,omitempty"`
	// Avatar URL or identifier
	Avatar *string `json:"avatar,omitempty"`
	// Timezone of the subscriber
	Timezone *string `json:"timezone,omitempty"`
	// Locale of the subscriber
	Locale *string `json:"locale,omitempty"`
	// Additional custom data for the subscriber
	Data map[string]any `json:"data,omitempty"`
}

func (p *PatchSubscriberRequestDto) GetFirstName() *string {
	if p == nil {
		return nil
	}
	return p.FirstName
}

func (p *PatchSubscriberRequestDto) GetLastName() *string {
	if p == nil {
		return nil
	}
	return p.LastName
}

func (p *PatchSubscriberRequestDto) GetEmail() *string {
	if p == nil {
		return nil
	}
	return p.Email
}

func (p *PatchSubscriberRequestDto) GetPhone() *string {
	if p == nil {
		return nil
	}
	return p.Phone
}

func (p *PatchSubscriberRequestDto) GetAvatar() *string {
	if p == nil {
		return nil
	}
	return p.Avatar
}

func (p *PatchSubscriberRequestDto) GetTimezone() *string {
	if p == nil {
		return nil
	}
	return p.Timezone
}

func (p *PatchSubscriberRequestDto) GetLocale() *string {
	if p == nil {
		return nil
	}
	return p.Locale
}

func (p *PatchSubscriberRequestDto) GetData() map[string]any {
	if p == nil {
		return nil
	}
	return p.Data
}
