// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type PhoneEndpointDto struct {
	// Phone number in E.164 format
	PhoneNumber string `json:"phoneNumber"`
}

func (p PhoneEndpointDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PhoneEndpointDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"phoneNumber"}); err != nil {
		return err
	}
	return nil
}

func (p *PhoneEndpointDto) GetPhoneNumber() string {
	if p == nil {
		return ""
	}
	return p.PhoneNumber
}
