// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlanUsageDto struct {
	// Current usage count for the resource in this environment.
	Used float64 `json:"used"`
	// Amount included in the organization plan.
	Limit float64 `json:"limit"`
}

func (p *PlanUsageDto) GetUsed() float64 {
	if p == nil {
		return 0.0
	}
	return p.Used
}

func (p *PlanUsageDto) GetLimit() float64 {
	if p == nil {
		return 0.0
	}
	return p.Limit
}
