// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type PreviewErrorDto struct {
	// Short error title
	Title string `json:"title"`
	// Detailed error message
	Message string `json:"message"`
	// Actionable hint for the user
	Hint string `json:"hint"`
}

func (p PreviewErrorDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PreviewErrorDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"title", "message", "hint"}); err != nil {
		return err
	}
	return nil
}

func (p *PreviewErrorDto) GetTitle() string {
	if p == nil {
		return ""
	}
	return p.Title
}

func (p *PreviewErrorDto) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *PreviewErrorDto) GetHint() string {
	if p == nil {
		return ""
	}
	return p.Hint
}
