// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/internal/utils"
)

type PushControlDto struct {
	// JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
	Skip map[string]any `json:"skip,omitempty"`
	// Subject/title of the push notification.
	Subject *string `json:"subject,omitempty"`
	// Body content of the push notification.
	Body *string `json:"body,omitempty"`
}

func (p PushControlDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PushControlDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PushControlDto) GetSkip() map[string]any {
	if o == nil {
		return nil
	}
	return o.Skip
}

func (o *PushControlDto) GetSubject() *string {
	if o == nil {
		return nil
	}
	return o.Subject
}

func (o *PushControlDto) GetBody() *string {
	if o == nil {
		return nil
	}
	return o.Body
}
