// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/novuhq/novu-go/v3/internal/utils"
)

// Target attribute for the redirect link
type Target string

const (
	TargetSelf        Target = "_self"
	TargetBlank       Target = "_blank"
	TargetParent      Target = "_parent"
	TargetTop         Target = "_top"
	TargetUnfencedTop Target = "_unfencedTop"
)

func (e Target) ToPointer() *Target {
	return &e
}
func (e *Target) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "_self":
		fallthrough
	case "_blank":
		fallthrough
	case "_parent":
		fallthrough
	case "_top":
		fallthrough
	case "_unfencedTop":
		*e = Target(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Target: %v", v)
	}
}

type RedirectDto struct {
	// URL to redirect to
	URL string `json:"url"`
	// Target attribute for the redirect link
	Target *Target `json:"target,omitempty"`
}

func (r RedirectDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RedirectDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"url"}); err != nil {
		return err
	}
	return nil
}

func (r *RedirectDto) GetURL() string {
	if r == nil {
		return ""
	}
	return r.URL
}

func (r *RedirectDto) GetTarget() *Target {
	if r == nil {
		return nil
	}
	return r.Target
}
