// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RemoveSubscribersRequestDto struct {
	// List of subscriber identifiers that will be removed to the topic
	Subscribers []string `json:"subscribers"`
}

func (o *RemoveSubscribersRequestDto) GetSubscribers() []string {
	if o == nil {
		return []string{}
	}
	return o.Subscribers
}
