// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResourceDependencyDto struct {
	// Type of the layout
	ResourceType ResourceTypeEnum `json:"resourceType"`
	// ID of the dependent resource
	ResourceID string `json:"resourceId"`
	// Name of the dependent resource
	ResourceName string `json:"resourceName"`
	// Whether this dependency blocks the operation
	IsBlocking bool `json:"isBlocking"`
	// Reason for the dependency
	Reason DependencyReasonEnum `json:"reason"`
}

func (r *ResourceDependencyDto) GetResourceType() ResourceTypeEnum {
	if r == nil {
		return ResourceTypeEnum("")
	}
	return r.ResourceType
}

func (r *ResourceDependencyDto) GetResourceID() string {
	if r == nil {
		return ""
	}
	return r.ResourceID
}

func (r *ResourceDependencyDto) GetResourceName() string {
	if r == nil {
		return ""
	}
	return r.ResourceName
}

func (r *ResourceDependencyDto) GetIsBlocking() bool {
	if r == nil {
		return false
	}
	return r.IsBlocking
}

func (r *ResourceDependencyDto) GetReason() DependencyReasonEnum {
	if r == nil {
		return DependencyReasonEnum("")
	}
	return r.Reason
}
