// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// SeverityLevelEnum - Severity of the workflow
type SeverityLevelEnum string

const (
	SeverityLevelEnumHigh   SeverityLevelEnum = "high"
	SeverityLevelEnumMedium SeverityLevelEnum = "medium"
	SeverityLevelEnumLow    SeverityLevelEnum = "low"
	SeverityLevelEnumNone   SeverityLevelEnum = "none"
)

func (e SeverityLevelEnum) ToPointer() *SeverityLevelEnum {
	return &e
}
func (e *SeverityLevelEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "high":
		fallthrough
	case "medium":
		fallthrough
	case "low":
		fallthrough
	case "none":
		*e = SeverityLevelEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SeverityLevelEnum: %v", v)
	}
}
