// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/internal/utils"
)

type SmsControlDto struct {
	// JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
	Skip map[string]any `json:"skip,omitempty"`
	// Content of the SMS message.
	Body *string `json:"body,omitempty"`
}

func (s SmsControlDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SmsControlDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *SmsControlDto) GetSkip() map[string]any {
	if o == nil {
		return nil
	}
	return o.Skip
}

func (o *SmsControlDto) GetBody() *string {
	if o == nil {
		return nil
	}
	return o.Body
}
