// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SubscriberGlobalPreferenceDto struct {
	// Whether notifications are enabled globally
	Enabled bool `json:"enabled"`
	// Channel-specific preference settings
	Channels SubscriberPreferenceChannels `json:"channels"`
	// Subscriber schedule
	Schedule *ScheduleDto `json:"schedule,omitempty"`
}

func (s *SubscriberGlobalPreferenceDto) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *SubscriberGlobalPreferenceDto) GetChannels() SubscriberPreferenceChannels {
	if s == nil {
		return SubscriberPreferenceChannels{}
	}
	return s.Channels
}

func (s *SubscriberGlobalPreferenceDto) GetSchedule() *ScheduleDto {
	if s == nil {
		return nil
	}
	return s.Schedule
}
