// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Subscriber - The subscriber information
type Subscriber struct {
	// The identifier of the subscriber
	ID string `json:"_id"`
	// The external identifier of the subscriber
	SubscriberID string `json:"subscriberId"`
	// The avatar URL of the subscriber
	Avatar *string `json:"avatar,omitempty"`
	// The first name of the subscriber
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the subscriber
	LastName *string `json:"lastName,omitempty"`
	// The email of the subscriber
	Email *string `json:"email,omitempty"`
}

func (s *Subscriber) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Subscriber) GetSubscriberID() string {
	if s == nil {
		return ""
	}
	return s.SubscriberID
}

func (s *Subscriber) GetAvatar() *string {
	if s == nil {
		return nil
	}
	return s.Avatar
}

func (s *Subscriber) GetFirstName() *string {
	if s == nil {
		return nil
	}
	return s.FirstName
}

func (s *Subscriber) GetLastName() *string {
	if s == nil {
		return nil
	}
	return s.LastName
}

func (s *Subscriber) GetEmail() *string {
	if s == nil {
		return nil
	}
	return s.Email
}

type SubscriptionResponseDto struct {
	// The unique identifier of the subscription
	ID string `json:"_id"`
	// The identifier of the subscription
	Identifier *string `json:"identifier,omitempty"`
	// The name of the subscription
	Name *string `json:"name,omitempty"`
	// The topic information
	Topic TopicDto `json:"topic"`
	// The subscriber information
	Subscriber *Subscriber `json:"subscriber"`
	// The preferences for workflows in this subscription
	Preferences []SubscriptionPreferenceDto `json:"preferences,omitempty"`
	// The creation date of the subscription
	CreatedAt string `json:"createdAt"`
	// The last update date of the subscription
	UpdatedAt string `json:"updatedAt"`
}

func (s *SubscriptionResponseDto) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SubscriptionResponseDto) GetIdentifier() *string {
	if s == nil {
		return nil
	}
	return s.Identifier
}

func (s *SubscriptionResponseDto) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SubscriptionResponseDto) GetTopic() TopicDto {
	if s == nil {
		return TopicDto{}
	}
	return s.Topic
}

func (s *SubscriptionResponseDto) GetSubscriber() *Subscriber {
	if s == nil {
		return nil
	}
	return s.Subscriber
}

func (s *SubscriptionResponseDto) GetPreferences() []SubscriptionPreferenceDto {
	if s == nil {
		return nil
	}
	return s.Preferences
}

func (s *SubscriptionResponseDto) GetCreatedAt() string {
	if s == nil {
		return ""
	}
	return s.CreatedAt
}

func (s *SubscriptionResponseDto) GetUpdatedAt() string {
	if s == nil {
		return ""
	}
	return s.UpdatedAt
}
