// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SubscriptionErrorDto struct {
	// The subscriber ID that failed
	SubscriberID string `json:"subscriberId"`
	// The error code
	Code string `json:"code"`
	// The error message
	Message string `json:"message"`
}

func (s *SubscriptionErrorDto) GetSubscriberID() string {
	if s == nil {
		return ""
	}
	return s.SubscriberID
}

func (s *SubscriptionErrorDto) GetCode() string {
	if s == nil {
		return ""
	}
	return s.Code
}

func (s *SubscriptionErrorDto) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}
