// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SubscriberPreferenceChannels struct {
	// Email channel preference
	Email *bool `json:"email,omitempty"`
	// SMS channel preference
	Sms *bool `json:"sms,omitempty"`
	// In-app channel preference
	InApp *bool `json:"in_app,omitempty"`
	// Chat channel preference
	Chat *bool `json:"chat,omitempty"`
	// Push notification channel preference
	Push *bool `json:"push,omitempty"`
}

func (s *SubscriberPreferenceChannels) GetEmail() *bool {
	if s == nil {
		return nil
	}
	return s.Email
}

func (s *SubscriberPreferenceChannels) GetSms() *bool {
	if s == nil {
		return nil
	}
	return s.Sms
}

func (s *SubscriberPreferenceChannels) GetInApp() *bool {
	if s == nil {
		return nil
	}
	return s.InApp
}

func (s *SubscriberPreferenceChannels) GetChat() *bool {
	if s == nil {
		return nil
	}
	return s.Chat
}

func (s *SubscriberPreferenceChannels) GetPush() *bool {
	if s == nil {
		return nil
	}
	return s.Push
}
