// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TemplateResponse struct {
	// Unique identifier of the workflow
	ID string `json:"_id"`
	// Name of the workflow
	Name string `json:"name"`
	// Critical templates will always be delivered to the end user and should be hidden from the subscriber preferences screen
	Critical bool `json:"critical"`
	// Triggers are the events that will trigger the workflow.
	Triggers []NotificationTriggerResponse `json:"triggers"`
}

func (o *TemplateResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *TemplateResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *TemplateResponse) GetCritical() bool {
	if o == nil {
		return false
	}
	return o.Critical
}

func (o *TemplateResponse) GetTriggers() []NotificationTriggerResponse {
	if o == nil {
		return []NotificationTriggerResponse{}
	}
	return o.Triggers
}
