// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type Data struct {
}

func (d Data) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Data) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

type TenantPayloadDto struct {
	Identifier *string `json:"identifier,omitempty"`
	Name       *string `json:"name,omitempty"`
	Data       *Data   `json:"data,omitempty"`
}

func (t TenantPayloadDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TenantPayloadDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TenantPayloadDto) GetIdentifier() *string {
	if t == nil {
		return nil
	}
	return t.Identifier
}

func (t *TenantPayloadDto) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TenantPayloadDto) GetData() *Data {
	if t == nil {
		return nil
	}
	return t.Data
}
