// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/internal/utils"
)

type TenantPayloadDtoData struct {
}

func (t TenantPayloadDtoData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TenantPayloadDtoData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

type TenantPayloadDto struct {
	Identifier *string               `json:"identifier,omitempty"`
	Name       *string               `json:"name,omitempty"`
	Data       *TenantPayloadDtoData `json:"data,omitempty"`
}

func (t TenantPayloadDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TenantPayloadDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *TenantPayloadDto) GetIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.Identifier
}

func (o *TenantPayloadDto) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TenantPayloadDto) GetData() *TenantPayloadDtoData {
	if o == nil {
		return nil
	}
	return o.Data
}
