// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentReply - Parsed JSON body from the agent webhook response when JSON.
type AgentReply struct {
}

type TestDomainRouteAgentResultDto struct {
	AgentID    string  `json:"agentId"`
	HTTPStatus float64 `json:"httpStatus"`
	// Parsed JSON body from the agent webhook response when JSON.
	AgentReply *AgentReply `json:"agentReply,omitempty"`
	LatencyMs  float64     `json:"latencyMs"`
}

func (t *TestDomainRouteAgentResultDto) GetAgentID() string {
	if t == nil {
		return ""
	}
	return t.AgentID
}

func (t *TestDomainRouteAgentResultDto) GetHTTPStatus() float64 {
	if t == nil {
		return 0.0
	}
	return t.HTTPStatus
}

func (t *TestDomainRouteAgentResultDto) GetAgentReply() *AgentReply {
	if t == nil {
		return nil
	}
	return t.AgentReply
}

func (t *TestDomainRouteAgentResultDto) GetLatencyMs() float64 {
	if t == nil {
		return 0.0
	}
	return t.LatencyMs
}
