// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TimeRangeDto struct {
	// Start time
	Start string `json:"start"`
	// End time
	End string `json:"end"`
}

func (t *TimeRangeDto) GetStart() string {
	if t == nil {
		return ""
	}
	return t.Start
}

func (t *TimeRangeDto) GetEnd() string {
	if t == nil {
		return ""
	}
	return t.End
}
