// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type ToolApprovalCardReplyContentDto struct {
	// Novu tool-approval card descriptor (`type: "tool-approval-card"`). Used with `toolApprovalRequest` to render Approve/Deny UI.
	ToolApprovalCard map[string]any `json:"toolApprovalCard"`
	Files            []FileRefDto   `json:"files,omitempty"`
}

func (t ToolApprovalCardReplyContentDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolApprovalCardReplyContentDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"toolApprovalCard"}); err != nil {
		return err
	}
	return nil
}

func (t *ToolApprovalCardReplyContentDto) GetToolApprovalCard() map[string]any {
	if t == nil {
		return map[string]any{}
	}
	return t.ToolApprovalCard
}

func (t *ToolApprovalCardReplyContentDto) GetFiles() []FileRefDto {
	if t == nil {
		return nil
	}
	return t.Files
}
