// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TopicSubscriberDto struct {
	// Unique identifier for the organization
	OrganizationID string `json:"_organizationId"`
	// Unique identifier for the environment
	EnvironmentID string `json:"_environmentId"`
	// Unique identifier for the subscriber
	SubscriberID string `json:"_subscriberId"`
	// Unique identifier for the topic
	TopicID string `json:"_topicId"`
	// Key associated with the topic
	TopicKey string `json:"topicKey"`
	// External identifier for the subscriber
	ExternalSubscriberID string `json:"externalSubscriberId"`
}

func (t *TopicSubscriberDto) GetOrganizationID() string {
	if t == nil {
		return ""
	}
	return t.OrganizationID
}

func (t *TopicSubscriberDto) GetEnvironmentID() string {
	if t == nil {
		return ""
	}
	return t.EnvironmentID
}

func (t *TopicSubscriberDto) GetSubscriberID() string {
	if t == nil {
		return ""
	}
	return t.SubscriberID
}

func (t *TopicSubscriberDto) GetTopicID() string {
	if t == nil {
		return ""
	}
	return t.TopicID
}

func (t *TopicSubscriberDto) GetTopicKey() string {
	if t == nil {
		return ""
	}
	return t.TopicKey
}

func (t *TopicSubscriberDto) GetExternalSubscriberID() string {
	if t == nil {
		return ""
	}
	return t.ExternalSubscriberID
}
