// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateChannelConnectionRequestDto struct {
	Workspace WorkspaceDto `json:"workspace"`
	Auth      AuthDto      `json:"auth"`
}

func (u *UpdateChannelConnectionRequestDto) GetWorkspace() WorkspaceDto {
	if u == nil {
		return WorkspaceDto{}
	}
	return u.Workspace
}

func (u *UpdateChannelConnectionRequestDto) GetAuth() AuthDto {
	if u == nil {
		return AuthDto{}
	}
	return u.Auth
}
