// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

// ControlValues - Control values for the layout. Omit to leave unchanged, or set to null to clear stored control values.
type ControlValues struct {
	// Email layout controls
	Email *EmailControlsDto `json:"email,omitempty"`
}

func (c *ControlValues) GetEmail() *EmailControlsDto {
	if c == nil {
		return nil
	}
	return c.Email
}

type UpdateLayoutDto struct {
	// Name of the layout
	Name string `json:"name"`
	// Enable or disable translations for this layout
	IsTranslationEnabled *bool `default:"false" json:"isTranslationEnabled"`
	// Control values for the layout. Omit to leave unchanged, or set to null to clear stored control values.
	ControlValues *ControlValues `json:"controlValues,omitempty"`
}

func (u UpdateLayoutDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLayoutDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLayoutDto) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateLayoutDto) GetIsTranslationEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsTranslationEnabled
}

func (u *UpdateLayoutDto) GetControlValues() *ControlValues {
	if u == nil {
		return nil
	}
	return u.ControlValues
}
