// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/novuhq/novu-go/v3/internal/utils"
)

type WebhookEndpointDto struct {
	// Webhook URL
	URL string `json:"url"`
	// Optional channel identifier
	Channel *string `json:"channel,omitempty"`
}

func (w WebhookEndpointDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookEndpointDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"url"}); err != nil {
		return err
	}
	return nil
}

func (w *WebhookEndpointDto) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *WebhookEndpointDto) GetChannel() *string {
	if w == nil {
		return nil
	}
	return w.Channel
}
