// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
)

type TopicResponseDto struct {
	// The identifier of the topic
	ID string `json:"_id"`
	// The unique key of the topic
	Key string `json:"key"`
	// The name of the topic
	Name *string `json:"name,omitempty"`
	// The date the topic was created
	CreatedAt *string `json:"createdAt,omitempty"`
	// The date the topic was last updated
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

var _ error = &TopicResponseDto{}

func (e *TopicResponseDto) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
